
package com.rh.oa.zh.seal.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSServer", targetNamespace = "http://100.16.5.55:8080/services/WSServer.jws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSServer {


    /**
     * 
     * @param deptId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getSealsByDeptIdReturn", targetNamespace = "http://ws.dj.com")
    @RequestWrapper(localName = "getSealsByDeptId", targetNamespace = "http://ws.dj.com", 
    className = "com.rh.oa.zh.seal.client.GetSealsByDeptId")
    @ResponseWrapper(localName = "getSealsByDeptIdResponse", targetNamespace = "http://ws.dj.com", 
    className = "com.rh.oa.zh.seal.client.GetSealsByDeptIdResponse")
    public String getSealsByDeptId(
        @WebParam(name = "deptId", targetNamespace = "http://ws.dj.com")
        String deptId);
    
    
    /**
     * 设置文件打印分数。
     * @param str 格式数据。每组字符串中有三个内容，分别是：机构编号,文档编号,打印总分数,  这三个参数分别中","分隔，组合成一组数据,每组数据用“;”分隔
例如："11,abcdeffasdf,19;21,askdfjasdfks,26"

     * @return
     *     returns 1 参数为空 ，2 参数格式异常 3 成功 4 文档编号不存在
     */
    @WebMethod
    @WebResult(name = "lssuedDocPrintReturn", targetNamespace = "http://ws.dj.com")
    @RequestWrapper(localName = "lssuedDocPrint", targetNamespace = "http://ws.dj.com", 
    className = "com.rh.oa.zh.seal.client.LssuedDocPrint")
    @ResponseWrapper(localName = "lssuedDocPrintResponse", targetNamespace = "http://ws.dj.com", 
    className = "com.rh.oa.zh.seal.client.LssuedDocPrintResponse")
    public String lssuedDocPrint(
        @WebParam(name = "str", targetNamespace = "http://ws.dj.com")
        String str);    
}
