package com.rh.oa.zh.seal.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSServerService")
public class WSServerService extends Service {

    /** web service 地址 **/
    private String serviceUrl = null;
    
    /**
     * 
     * @param wsdlLocation A URL pointing to the WSDL document
     *        for the service, or <code>null</code> if there isn't one.
     * @param serviceName The qualified name of the servic
     */
    private WSServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @param wsdlUrl wsdl文件地址
     * @return WSServerService 对象
     * @throws MalformedURLException 一个错误URL产生的Exception
     */
    public static WSServerService createWSServerService(String wsdlUrl) throws MalformedURLException {

        URL wsdlLocation = new URL(wsdlUrl + "?wsdl");
        QName serviceName = new QName(wsdlUrl, "WSServerService");

        WSServerService service = new WSServerService(wsdlLocation, serviceName);

        service.serviceUrl = wsdlUrl;

        return service;
    }

    /**
     * 
     * @return returns WSServer
     */
    @WebEndpoint(name = "WSServer")
    public WSServer getWSServer() {
        return super.getPort(new QName(serviceUrl, "WSServer"), WSServer.class);
    }

    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features
     *            not in the <code>features</code> parameter will have their default values.
     * @return returns WSServer
     */
    @WebEndpoint(name = "WSServer")
    public WSServer getWSServer(WebServiceFeature... features) {
        return super.getPort(new QName(serviceUrl, "WSServer"), WSServer.class,
                features);
    }

}
