function aC(a,b){var c=j;if("delete"===b&&(c=uk.Ar?"debugger":window.prompt("请输入删除理由"),!c))return;a.xhr=new Y(i);a.eb&&Q(a.e(),a.xhr,"success",a.ne);a.xhr.ajax("/reviewq/answer?queue_id="+a.Cb+"&is_realm="+a.Vd,"action="+b+"&answer_id="+a.U.getAttribute("data-answer_id")+"&task_id="+a.U.getAttribute("data-task_id")+(c?"&reason="+c:"")+"&none_queue="+a.U.getAttribute("data-none_queue"))}
function bC(a,b){a.xhr=new Y(i);a.eb&&Q(a.e(),a.xhr,"success",a.ne);a.xhr.ajax("/reviewq/question?queue_id="+a.Cb+"&is_realm="+a.Vd,"action="+b+"&question_id="+a.U.getAttribute("data-question_id")+"&task_id="+a.U.getAttribute("data-task_id")+"&none_queue="+a.U.getAttribute("data-none_queue"))}var cC=["delete","delete_answer"];function dC(a){if(z&&!Gb(9)){var b=l;try{b=a.parentNode}catch(c){}return!!b}return uc(a.ownerDocument.body,a)}function eC(a,b){return a.W.f(b?a.$G:a.qC)}
function fC(a){if("outerHTML"in a)return a.outerHTML;var b=Ub(a).createElement("div");b.appendChild(a.cloneNode(i));return b.innerHTML}function gC(a,b){return da[a]=b}ar.prototype.Pf=gC(41,function(){var a=this.wq.body.createTextRange();a.moveToElementText(this.wq.body);return this.rg(new ar(a,this.wq),i)});kr.prototype.Pf=gC(40,function(){return(!this.na||dC(this.na))&&(!this.ia||dC(this.ia))&&(!(z&&!Gb(9))||or(this).Pf())});
qr.prototype.Pf=gC(39,function(){var a=l;try{a=y.every(this.Jh(),function(a){return z?!!a.parentNode:uc(a.ownerDocument.body,a)})}catch(b){}return a});wr.prototype.Pf=gC(38,function(){return y.every(Lq(this),function(a){return a.Pf()})});Sq.prototype.$i=gC(37,function(){return 3!=this.X.nodeType?-1:this.X==this.na?this.ta:0});ur.prototype.$i=gC(36,p(0));yr.prototype.$i=gC(35,function(){return this.Qf[this.Mk].$i()});
Jz.prototype.aw=gC(34,function(a,b,c,d,f){var g=f||"question",a="question"===g?"问题":"答案";y.contains(cC,d)?Ol({title:c+a,content:"确定要"+c+"这个"+a+"吗？",zi:["取消","确定"+c]},function(a){a?"question"===g?bC(this,d):aC(this,d):this.locked=l},this):"question"===g?bC(this,d):aC(this,d)});
Wq.prototype.Ud=gC(33,function(){var a=Sb(this.J.startContainer).j("div");a.appendChild(this.J.cloneContents());a=a.innerHTML;if(Fa(a,"<")||!this.isCollapsed()&&!$a(a,"<"))return a;var b=this.mc(),b=1==b.nodeType?b:b.parentNode;return fC(b.cloneNode(l)).replace(">",">"+a)});ar.prototype.Ud=gC(32,function(){return this.J.htmlText});kr.prototype.Ud=gC(31,function(){return or(this).Ud()});qr.prototype.Ud=gC(30,function(){return this.Cg()});wr.prototype.Ud=gC(29,function(){return y.map(Lq(this),function(a){return a.Ud()}).join("")});
Sq.prototype.Zi=gC(28,function(){return 3!=this.X.nodeType?-1:this.X==this.ia?this.sa:this.X.nodeValue.length});ur.prototype.Zi=gC(27,p(0));yr.prototype.Zi=gC(26,function(){return this.Qf[this.Mk].Zi()});Jq.prototype.Zf=gC(25,function(a){this.isCollapsed()||this.Ic();return this.insertNode(a,i)});qr.prototype.Zf=gC(24,function(a){a=this.insertNode(a,i);this.isCollapsed()||this.Ic();return a});
Gq.prototype.restore=gC(23,function(a){this.Ji&&Hq.log(ce,"Disposed SavedRange objects cannot be restored.",h);var b=this.Uj();a||this.w();return b});pr.prototype.Uj=gC(22,function(){return mr(this.QA,this.uJ,this.HC,this.GL)});vr.prototype.Uj=gC(21,function(){for(var a=(this.Ra.length?Ub(this.Ra[0]):document).body.createControlRange(),b=0,c=this.Ra.length;b<c;b++)a.addElement(this.Ra[b]);return rr(a)});
zr.prototype.Uj=gC(20,function(){var a=y.map(this.Ny,function(a){return a.restore()}),b=new wr;b.Ml=a;b.Pe=y.map(a,function(a){return a.Qd()});return b});Vw.prototype.Jg=gC(19,function(){return 0<=this.Sf-this.Kd.value.length});Wz.prototype.Jg=gC(18,function(){return bA(this)});
Uq.prototype.Cg=gC(17,function(){var a=new Tq;O.forEach(this,function(b,c,d){3==b.nodeType?a.append(Ra(b.nodeValue.substring(d.$i(),d.Zi()))):1==b.nodeType&&(-1==d.Qb?ic(b)&&a.append("</"+b.tagName+">"):(c=b.cloneNode(l),c=fC(c),z&&"LI"==b.tagName?a.append(c):(b=c.lastIndexOf("<"),a.append(b?c.substr(0,b):c))))},this);return a.toString()});kr.prototype.Cg=gC(16,function(){return or(this).Cg()});qr.prototype.Cg=gC(15,function(){return y.map(tr(this),fC).join("")});wr.prototype.Cg=gC(14,function(){return this.Ud()});
Iq.prototype.Yo=gC(13,function(){var a=this.Bc?-1:1;this.Qb==a&&(this.Qb=-1*a,this.depth+=this.Qb*(this.Bc?-1:1))});Sq.prototype.Yo=gC(12,function(){Sq.g.Yo.apply(this);uc(this.X,this.ia)&&e(O.Ta)});$d.prototype.zB=gC(11,function(a,b){this.log(fe,a,b)});Id.prototype.setInterval=gC(10,function(a){this.Gg=a;this.ga&&this.enabled?(this.stop(),this.start()):this.ga&&this.stop()});uo.prototype.Rv=gC(9,function(){return this.f().innerHTML});
Rq.prototype.Yg=gC(8,function(a,b){this.insertNode(a,i);this.insertNode(b,l)});Wq.prototype.Yg=gC(7,function(a,b){var c=cc(Ub(this.M()));if(c=Ar(c))var d=c.M(),f=c.ba(),g=c.ma(),k=c.Ba();var m=this.J.cloneRange(),q=this.J.cloneRange();m.collapse(l);q.collapse(i);m.insertNode(b);q.insertNode(a);m.detach();q.detach();if(c){if(3==d.nodeType)for(;g>d.length;){g-=d.length;do d=d.nextSibling;while(d==a||d==b)}if(3==f.nodeType)for(;k>f.length;){k-=f.length;do f=f.nextSibling;while(f==a||f==b)}mr(d,g,f,k).select()}});
ar.prototype.Yg=gC(6,function(a,b){var c=this.J.duplicate(),d=this.J.duplicate();gr(c,a,i);gr(d,b,l);this.oe()});kr.prototype.Yg=gC(5,function(a,b){or(this).Yg(a,b);this.oe()});Wq.prototype.Ic=gC(4,function(){var a=this.J;a.extractContents();if(a.startContainer.hasChildNodes()&&(a=a.startContainer.childNodes[a.startOffset])){var b=a.previousSibling;""==Ic(a)&&L(a);b&&""==Ic(b)&&L(b)}});
ar.prototype.Ic=gC(3,function(){if(!this.isCollapsed()&&this.J.htmlText){var a=this.M(),b=this.ba(),c=this.J.text,d=this.J.duplicate();d.moveStart("character",1);d.moveStart("character",-1);d.text==c&&(this.J=d);this.J.text="";this.oe();c=this.M();d=this.ma();try{var f=a.nextSibling;a==b&&(a.parentNode&&3==a.nodeType&&f&&3==f.nodeType)&&(a.nodeValue+=f.nodeValue,L(f),this.J=cr(c),this.J.move("character",d),this.oe())}catch(g){}}});kr.prototype.Ic=gC(2,function(){or(this).Ic();this.oe()});
qr.prototype.Ic=gC(1,function(){if(this.J){for(var a=[],b=0,c=this.J.length;b<c;b++)a.push(this.J.item(b));y.forEach(a,L);this.collapse(l)}});wr.prototype.Ic=gC(0,function(){y.forEach(Lq(this),function(a){a.Ic()})});function hC(a,b){var c=b.Wc();a.Hc[c]&&a.Ob.log(ce,"Cannot register the same class of plugin twice.",h);a.Hc[c]=b;for(var d in Es)b[Es[d]]&&a.oj[d].push(b);b.o=a;a.wd()&&b.enable(a)}function iC(a){return a.o&&a.o.Ya}
function jC(a){var b=a.X.parentNode;return new ns(b,y.indexOf(b.childNodes,a.X))}function kC(a,b,c,d){return mr(a,b,c,d)}function lC(a){M.call(this);this.$G=fb();this.qC=fb();this.W=Sb(a.va());a.Yg(this.W.j("SPAN",{id:this.$G}),this.W.j("SPAN",{id:this.qC}))}w(lC,Gq);lC.prototype.Bo=function(a){L(eC(this,i));L(eC(this,l));return a};
lC.prototype.Uj=function(){var a=j,b=eC(this,i),c=eC(this,l);if(b&&c){var a=b.parentNode,b=y.indexOf(a.childNodes,b),d=c.parentNode,c=y.indexOf(d.childNodes,c);d==a&&(c-=1);a=mr(a,b,d,c);a=this.Bo(a);a.select()}else this.Bo();return a};lC.prototype.m=function(){this.Bo();this.W=j};function mC(a){var b;if(3==a.X.nodeType)for(b=a.X.previousSibling;b&&3==b.nodeType;b=b.previousSibling)a.offset+=is(b);else b=a.X.previousSibling;var c=a.X.parentNode;a.X=b?b.nextSibling:c.firstChild;return a}
function nC(a,b){return b?ms(a.M(),a.ma()):ms(a.ba(),a.Ba())}function oC(a){for(var b=j,c=a.firstChild;c;){var d=c.nextSibling;3==c.nodeType?""==c.nodeValue?a.removeChild(c):b?(b.nodeValue+=c.nodeValue,a.removeChild(c)):b=c:(oC(c),b=j);c=d}}function pC(a){var b=a&&a.nodeName.toLowerCase();return!(!a||"block"!=(1!=a.nodeType?j:z?Wf(a,"display"):Vf(a,"display"))&&!("td"==b||"table"==b||"li"==b))}function qC(a){return Kc(a,pC,i)}
function rC(a,b){if(b){var c,d=mC(nC(b,i)),f=jC(d),g=d.X.previousSibling;3==d.X.nodeType&&(d.X=j);var k=mC(nC(b,l)),m=jC(k),q=k.X.previousSibling;3==k.X.nodeType&&(k.X=j);c=function(){!d.X&&g&&(d.X=g.nextSibling,d.X||(d=new ns(g,is(g))));!k.X&&q&&(k.X=q.nextSibling,k.X||(k=new ns(q,is(q))));return mr(d.X||f.X.firstChild||f.X,d.offset,k.X||m.X.firstChild||m.X,k.offset)};var s=qC(b.Db())}s?(s=yc(s,a),z?oC(s):s.normalize()):a&&(z?oC(a):a.normalize());return c?c():j}
function sC(a){return a.getAttribute&&"true"==a.getAttribute("g_editable")}function tC(a,b,c){rh.call(this,b,a||Hh.v(),c)}w(tC,rh);function uC(a){lC.call(this,a)}w(uC,lC);uC.prototype.Bo=function(a){var b=eC(this,i),c=eC(this,l),b=b&&c?yc(b,c):b||c;uC.g.Bo.call(this);if(a)return rC(b,a);b&&(a=Ar(cc(Ub(b))),(a=rC(b,a))&&a.select())};
function vC(a,b,c){for(var d=(b=1==b)?a.M():a.ba(),f=b?a.ma():a.Ba(),g=a.Db();d!=g&&d!=c&&!(b&&0!=f||!b&&f!=is(d));)var k=d.parentNode,d=y.indexOf(k.childNodes,d),f=b?d:d+1,d=k;return kC(b?d:a.M(),b?f:a.ma(),b?a.ba():d,b?a.Ba():f)}
function wC(a){vg(a,l);if(Lr)for(var b=a,a=a.parentNode;a&&"HTML"!=a.tagName;){if(ug?"none"==a.style[ug].toLowerCase():(z||tb)&&"on"==a.getAttribute("unselectable")){vg(a,l,i);for(var c=0,d=a.childNodes.length;c<d;c++){var f=a.childNodes[c];f!=b&&1==f.nodeType&&vg(a.childNodes[c],i)}}b=a;a=a.parentNode}}function xC(a){var b=a.target.tagName;"TEXTAREA"!=b&&"INPUT"!=b&&a.preventDefault()}function yC(a){var b=a.Db();return a.M()!=b.parentElement&&sC(b)||!!Kc(b,sC)}
function zC(a,b){var c=vC(a,1,b),c=vC(c,0,b),d=c.M(),f=c.ba(),g=c.ma(),c=c.Ba();if(d==f){for(;f!=b&&0==g&&c==is(f);)d=f.parentNode,g=y.indexOf(d.childNodes,f),c=g+1,f=d;d=f}return mr(d,g,f,c)}function AC(a,b){Lr&&b.c(a,"mousedown",xC,i);vg(a,i);for(var c=a.getElementsByTagName("INPUT"),d=0,f=c.length;d<f;d++){var g=c[d];g.type in js&&wC(g)}y.forEach(a.getElementsByTagName("TEXTAREA"),wC)}function BC(a){return!!ds[a.tagName]}
function CC(a,b){var c=Ic(a);if(a.getElementsByTagName)for(var d in es)if(a.tagName==d||0<a.getElementsByTagName(d).length)return l;return!b&&" "==c||Ka(c)}function DC(a){return gs(O.filter(new bs(a),hs))}var EC;function FC(a){var b=arguments,c=b.length;return function(){for(var a=0;a<c;a++)if(!b[a].apply(this,arguments))return l;return i}}var GC;function HC(a){this.xf=a;this.rO=i;this.Bv=[]}function IC(a){a.Zu||(a.Zu=Ic(a.xf));return a.Zu};function JC(){Ds.call(this)}w(JC,Ds);JC.prototype.Wc=p("BTF");JC.prototype.Ob=le("goog.editor.plugins.BasicTextFormatter");var KC=F.im({rI:"+link",dV:"+formatBlock",pV:"+indent",QV:"+outdent",tW:"+strikeThrough",mV:"+insertHorizontalRule",uW:"+subscript",vW:"+superscript",HW:"+underline",GU:"+bold",rV:"+italic",bV:"+fontSize",aV:"+fontName",$U:"+foreColor",AU:"+backColor",OV:"+insertOrderedList",LW:"+insertUnorderedList",sV:"+justifyCenter",tV:"+justifyFull",vV:"+justifyRight",uV:"+justifyLeft"});
r=JC.prototype;r.De=function(a){return a in KC};r.se=function(){return ft(this.o)};function LC(a){return iC(a).va()}
r.Ve=function(a,b){var c,d,f,g,k,m=b;switch(a){case "+backColor":if(m!==j)if(Rr){d=m;f=ft(this.o);var q,s;f&&f.isCollapsed()&&(q=iC(this).createTextNode(A?" ":""),m=f.M(),s=1==m.nodeType?m:m.parentNode,""==s.innerHTML?(s.style.textIndent="-10000px",s.appendChild(q)):(s=iC(this).j("span",{style:"text-indent:-10000px"},q),f.Zf(s)),Pq(q).select());MC(this,"hiliteColor",d,l,i);q&&(A&&(q.data=""),s.style.textIndent="")}else tb?MC(this,"hiliteColor",m):MC(this,a,m);break;case "+link":a:{k=m;this.o.Ce||
iC(this).Ja().focus();f=(d=this.se())&&d.Db();if((f=Jc(f,"A"))&&Kc(f,sC))pc(f);else{f=j;var x=[];if((m=d&&d.Db())&&"IMG"==m.tagName)k=j;else{if(d&&d.isCollapsed())d=d.ue(0).Qd(),Hr?(f=iC(this).createElement("A"),d.insertNode(f)):Gr&&(d.pasteHTML("<a id='newLink'></a>"),f=iC(this).f("newLink"),f.removeAttribute("id"));else{var C=fb();MC(this,"CreateLink",C);y.forEach(this.o.f().getElementsByTagName("A"),function(a){Ga(a.href,C)&&x.push(a)});x.length&&(f=x.pop())}d=f;f=new HC(d);f.xf.href="/";k&&(d.target=
k);x&&(f.Bv=x);k=f}if(k){if(!this.o.execCommand("link",k))if(g=this.o.Dk.prompt(wj,"http://"))if(d=k,f=IC(k)||g,m=d.xf,m.href=g,q=IC(d),f!=q&&(g=fs(m),3==g.nodeType&&(g=g.parentNode),Ic(g)!=q&&(g=m),kc(g),m=Sb(g),g.appendChild(m.createTextNode(f)),d.Zu=j),d.rO=l,d=k.xf,Vr){f=d.nextSibling;if(!f||!(3==f.nodeType&&(Fa(f.data," ")||Fa(f.data," "))))f=Sb(d).createTextNode(" "),mc(f,d);Dr(f,1).select()}else ls(d,l);else{d=Pq(k.xf);d=new uC(d);pc(k.xf);for(k.xf=j;k.Bv.length;)pc(k.Bv.pop());d.restore().select();
k=j;break a}break a}}k=j}break;case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":MC(this,a,j,l,i);A&&MC(this,a,j,l,i);(!Pr||!A)&&O.forEach(ft(this.o),NC);break;default:z&&("+formatBlock"==a&&m)&&(m="<"+m+">");if("+foreColor"==a&&m===j)break;switch(a){case "+indent":case "+outdent":Pr&&(A&&(d=i),tb&&(d="+outdent"==a?!LC(this).queryCommandEnabled("outdent"):i));case "+insertOrderedList":case "+insertUnorderedList":if(q=Yr)q=LC(this),q=OC(this,i,q,a,h);if(q)f="P"!=this.o.queryCommandValue("+defaultTag");
else if(!Zr&&(z||tb)){c=this.se();q=c.Db();var J=LC(this);PC.lastIndex=0;PC.test(q.innerHTML)&&(c=c.M()&&c.ba()?new lC(c):j,"P"==q.tagName?QC(q,i):(q.innerHTML=q.innerHTML.replace(PC,'<p$1 trtempbr="temp_br">'),q=y.toArray(q.getElementsByTagName("P")),O.forEach(q,function(a){if("temp_br"==a.getAttribute("trtempbr")){a.removeAttribute("trtempbr");if(Ka(Gc(a))){var b=z?J.createTextNode(" "):J.createElement("BR");a.appendChild(b)}QC(a)}})),c.restore())}A&&(Xr&&!this.queryCommandValue(a))&&(q=this.o.queryCommandValue("+defaultTag"),
"P"==q||"DIV"==q?q=l:(q=this.se(),q.isCollapsed()&&3!=q.mc().nodeType?(c=iC(this).createTextNode(" "),q.insertNode(c,l),Pq(c).select(),q=i):q=l),g|=q);case "+formatBlock":c=!!this.o.Hc.Bidi;break;case "+subscript":case "+superscript":Wr&&!this.queryCommandValue(a)&&(q="+subscript"==a?"+superscript":"+subscript",s=RC(q),this.queryCommandValue(q)||LC(this).execCommand(s,l,j),LC(this).execCommand(s,l,j));break;case "+underline":case "+bold":case "+italic":d=A&&Pr&&this.queryCommandValue(a);break;case "+foreColor":case "+fontName":d=
Pr&&A}MC(this,a,m,c,!!d);g&&LC(this).execCommand("Delete",l,i);f&&LC(this).execCommand("FormatBlock",l,"<div>")}A&&!this.o.Fg&&iC(this).Ja().focus();return k};
r.queryCommandValue=function(a){var b;switch(a){case "+link":return a=(a=this.se())&&a.Db(),a=Jc(a,"A"),!!a&&!!Kc(a,sC);case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":return SC(this,a);case "+formatBlock":var a=ft(this.o),c=j;O.forEach(a,function(a,b,d){-1!=d.Qb&&(a=qC(a).tagName,c=c||a,c!=a&&(c=j,e(O.Ta)),d.Yo())});return c;case "+indent":case "+outdent":case "+insertHorizontalRule":return l;case "+fontSize":case "+fontName":case "+foreColor":case "+backColor":return this.xs(LC(this),
a,Pr&&A);case "+underline":case "+bold":case "+italic":b=Pr&&A;default:var d=LC(this);return OC(this,i,d,a,b)}};r.XF=function(a){Nr&&a.match(/^\s*<script/i)&&(a="&nbsp;"+a);Or&&(a=a.replace(/<(\/?)strong([^\w])/gi,"<$1b$2"),a=a.replace(/<(\/?)em([^\w])/gi,"<$1i$2"));return a};
r.jK=function(a){for(var a=a.getElementsByTagName("IMG"),b=0,c;c=a[b];b++)if(z){c.removeAttribute("tabIndex");c.removeAttribute("tabIndexSet");var d=c;"removeAttribute"in d&&d.removeAttribute(ua);try{delete d[ua]}catch(f){}c.wP&&(c.tabIndex=c.wP)}};r.kK=function(a){if(B){for(var b=Wb(this.o.Ya.Aa,"HEAD",h,h),c=[],d=b.length,f=1;f<d;++f)for(var g=b[f].getElementsByTagName("STYLE"),k=g.length,m=0;m<k;++m)c.push(g[m].outerHTML);return c.join("")+a}return a};
r.Zq=function(a,b,c){if(!c)return l;var d;switch(b){case "b":d="+bold";break;case "i":d="+italic";break;case "u":d="+underline";break;case "s":return i}return d?(this.o.execCommand(d),i):l};var PC=z?/<br([^\/>]*)\/?>/gi:/<br([^\/>]*)\/?>(?!<\/(div|p)>)/gi;function QC(a,b){if(z||tb){var c=a.outerHTML.replace(/<(\/?)p/gi,"<$1div");b&&(c=c.replace(PC,"</div><div$1>"));tb&&!/<\/div>$/i.test(c)&&(c+="</div>");a.outerHTML=c}}function RC(a){return 0==a.indexOf("+")?a.substring(1):a}
function NC(a){a=qC(a);a.align&&(a.style.textAlign=a.align,a.removeAttribute("align"))}
function MC(a,b,c,d,f){var g=j;d&&(g=a.o.queryCommandValue("rtl")?"rtl":a.o.queryCommandValue("ltr")?"ltr":j);var b=RC(b),k,m;if(z){var q=b;m=[];var d=j,s=a.se();k=iC(a);if(q in TC){var x=s&&s.Db();if(x){for(var C=Vb("BLOCKQUOTE",j,x),J,G=0;G<C.length;G++)if(s.containsNode(C[G])){J=C[G];break}if(x=J||Jc(x,"BLOCKQUOTE"))d=k.j("div",{style:"height:0"}),x.appendChild(d),m.push(d),J?s=mr(J,0,d,0):s.containsNode(d)&&(s=kC(s.M(),s.ma(),d,0)),s.select()}}J=a.o;!J.ic()&&!d&&q in UC&&(J=J.f(),s&&(s.isCollapsed()&&
!rc(J))&&(d=s.ue(0).Qd(),s=d.duplicate(),s.moveToElementText(J),s.collapse(l),s.isEqual(d)&&(s=k.createTextNode(" "),J.appendChild(s),d.move("character",1),d.move("character",-1),d.select(),m.push(s))),d=k.j("div",{style:"height:0"}),J.appendChild(d),m.push(d));k=m[0];m=m[1]}if(B){k=b;var P;VC[k]&&(P=iC(a).j("div",{style:"height: 0"},"x"),a.o.f().appendChild(P));WC[k]&&(k=a.o.f(),P=iC(a).j("div",{style:"height: 0"},"x"),k.insertBefore(P,k.firstChild));k=P}if(A&&(P=b,D("1.9")&&"formatblock"==P.toLowerCase()&&
(P=a.se(),J=P.M(),P.isCollapsed()&&(J&&"BODY"==J.tagName)&&(d=P.ma(),(J=J.childNodes[d])&&"BR"==J.tagName))))P=P.Qd(),P.setStart(J,0),P.setEnd(J,0);if($r&&"fontsize"==b.toLowerCase()){var W=zC(ft(a.o),a.o.f());O.forEach(O.filter(W,function(a,b,c){return 1==c.Qb&&W.containsNode(a)}),function(a){Rf(a,"font-size","");A&&(0==a.style.length&&a.getAttribute("style")!=j)&&a.removeAttribute("style")})}P=LC(a);if(f&&Pr&&(P.execCommand("styleWithCSS",l,i),tb)){J=[];d=ft(a.o).Db();do J.push(d);while(d=d.parentNode);
J=O.$J(O.Mc(ft(a.o)),O.Mc(J));J=O.filter(J,pC);O.forEach(J,function(a){var b=a.style.outline;a.style.outline="0px solid red";a.style.outline=b})}P.execCommand(b,l,c);f&&Pr&&P.execCommand("styleWithCSS",l,l);B&&(!D("526")&&"formatblock"==b.toLowerCase()&&c&&/^[<]?h\d[>]?$/i.test(c))&&O.forEach(a.se(),function(a){"Apple-style-span"==a.className&&(a.style.fontSize="",a.style.fontWeight="")});if(/insert(un)?orderedlist/i.test(b)){if(B){var ma=l;O.forEach(a.se(),function(a){var b=a.tagName;if("UL"==b||
"OL"==b)if(ma){if(b=tc(a)){var c=a.ownerDocument.createRange();c.setStartAfter(b);c.setEndBefore(a);if(Ja(c.toString())&&b.nodeName==a.nodeName){for(;b.lastChild;)a.insertBefore(b.lastChild,a.firstChild);b.parentNode.removeChild(b)}}}else ma=i})}if(z){for(b=(b=a.se())&&b.mc();b&&"UL"!=b.tagName&&"OL"!=b.tagName;)b=b.parentNode;b&&(b=b.parentNode);b&&(c=y.toArray(b.getElementsByTagName("UL")),y.extend(c,y.toArray(b.getElementsByTagName("OL"))),y.forEach(c,function(a){var b=a.type;if(b&&!("UL"==a.tagName?
XC:YC)[b])a.type=""}));m&&L(m)}}k&&L(k);g&&a.o.execCommand(g)}var UC={indent:1,outdent:1,insertOrderedList:1,insertUnorderedList:1,justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,ltr:1,rtl:1},TC={insertOrderedList:1,insertUnorderedList:1},YC={1:1,a:1,A:1,i:1,I:1},XC={disc:1,circle:1,square:1},VC={justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,formatBlock:1},WC={insertOrderedList:1,insertUnorderedList:1},ZC={center:1,justify:1,right:1,left:1};
function SC(a,b){var c=b.replace("+justify","").toLowerCase();"full"==c&&(c="justify");var d=a.o.Hc.Bidi;if(d)return c==d.OX();var f=a.se();if(!f)return l;for(var g=f.Db(),d=y.filter(g.childNodes,function(a){return hs(a)&&f.containsNode(a,i)}),d=d.length?d:[g],g=0;g<d.length;g++){var k=qC(d[g]),m=c,q=Xf(k,"textAlign"),q=q.replace(/^-(moz|webkit)-/,"");ZC[q]||(q=k.align||"left");if(m!=q)return l}return i}JC.prototype.xs=function(a,b,c){return OC(this,l,a,b,c)};
function OC(a,b,c,d,f){d=RC(d);if(f){var g=LC(a);g.execCommand("styleWithCSS",l,i)}a=b?c.queryCommandState(d):c.queryCommandValue(d);f&&g.execCommand("styleWithCSS",l,l);return a};function $C(a,b){M.call(this);this.gs=[];for(this.bs=[];a&&"BODY"!=a.nodeName&&a!=b;){for(var c=0,d=a.previousSibling;d;)d=d.previousSibling,++c;this.gs.unshift(c);this.bs.unshift(a.nodeName);a=a.parentNode}}w($C,M);$C.prototype.toString=function(){for(var a=[],b,c=0;b=this.bs[c];c++)a.push(this.gs[c]+","+b);return a.join("\n")};function aD(a,b){for(var c,d=b,f=0;c=a.bs[f];++f)if(d=d.childNodes[a.gs[f]],!d||d.nodeName!=c)return j;return d}$C.prototype.m=function(){delete this.gs;delete this.bs};le("goog.editor.plugins.Blockquote");function bD(){Ds.call(this)}w(bD,Ds);r=bD.prototype;r.hk="DIV";r.Wc=p("EnterHandler");r.enable=function(a){bD.g.enable.call(this,a);as&&("P"==this.hk||"DIV"==this.hk)&&iC(this).va().execCommand("opera-defaultBlock",l,this.hk)};r.XF=function(a){return!a||Ka(a)?Nr?this.VL():"":a};r.VL=mf("<br>");
r.GM=function(a){if(A&&this.o.Fg)return l;if(8==a.keyCode){var b=ft(this.o),c=this.o.f(),b=b&&b.M();c.firstChild==b&&CC(b)&&(a.preventDefault(),a.stopPropagation())}else if(13==a.keyCode)if(A){if(!a.shiftKey){var c=ft(this.o),b=!c||c.isCollapsed(),d=Hr?cD(this):dD(this),f=this.o.execCommand("+splitBlockquote",d);f&&(a.preventDefault(),a.stopPropagation());Hr||d.removeNode(i);f||this.yM(a,b,c)}}else{this.o.yh();c=Hr?cD(this):dD(this);if(b=!!this.o.execCommand("+splitBlockquote",c))a.preventDefault(),
a.stopPropagation();Hr||c.removeNode(i);B&&this.zM(a);if(z||tb)eD(this);else if(!b&&B){if(b=c=ft(this.o))a:{for(b=c.Db();b;b=b.parentNode)if(BC(b)){b="BLOCKQUOTE"==b.tagName;break a}b=l}if(b){b=iC(this);d=b.createElement("BR");c.insertNode(d,i);if(c=BC(d.parentNode)){for(c=d.nextSibling;c&&3==c.nodeType&&!c.nodeValue;)c=c.nextSibling;c=!c}c&&lc(b.createElement("BR"),d);ls(d,l);a.preventDefault()}}this.o.Se()}else if(A&&46==a.keyCode&&(b=ft(this.o),b.isCollapsed()&&(c=b.ba(),1==c.nodeType&&(b=c.childNodes[b.Ba()])&&
"BR"==b.tagName)))d=gs(O.filter(new bs(b,l,i),hs)),f=b.nextSibling,c.removeChild(b),a.preventDefault(),f&&BC(f)&&(d&&!("BR"==d.tagName||BC(d))?Dr(d,is(d)).select():(a=fs(f),Dr(a,0).select()));return l};r.Yq=function(a){if(A&&this.o.Fg)return l;(z||tb)&&13==a.keyCode&&eD(this,i);return l};r.zM=ia;r.yM=ia;var fD=F.xh("LI","DIV","H1","H2","H3","H4","H5","H6");
function eD(a,b){for(var c=ft(a.o),d=c.mc(),f=a.o.f(),g;d&&d!=f;){var k=d.nodeName;if("DIV"==k||fD[k]&&(!b||!(CC(d)&&1==d.getElementsByTagName("BR").length))){if(tb&&g){"DIV"==k&&(g==d.lastChild&&CC(g))&&(mc(g,d),Pq(g).select());break}return}tb&&(b&&"P"==k&&"DIV"!=k)&&(g=d);d=d.parentNode}if(z&&!D(9)){var m=l,c=c.Qd(),d=c.duplicate();d.moveEnd("character",1);if(d.text.length&&(m=d.parentElement(),d=d.duplicate(),d.collapse(l),d=d.parentElement(),m=m!=d&&d!=c.parentElement()))c.move("character",-1),
c.select()}a.o.Ya.va().execCommand("FormatBlock",l,"<DIV>");m&&(c.move("character",1),c.select())}function dD(a){var a=iC(a).va(),b=a.selection.createRange(),c=fb();b.pasteHTML('<span id="'+c+'"></span>');a=a.getElementById(c);a.id="";return a}
function cD(a){a=ft(a.o);if(!a.isCollapsed()){var b=i;if(tb){var c=a.M(),d=a.ma();c==a.ba()&&(c.lastChild&&"BR"==c.lastChild.tagName&&d==c.childNodes.length-1)&&(b=l)}if(b){var f=a;if(f&&!f.isCollapsed()){var g=i,b=f.Db(),c=new $C(f.M(),b),d=f.ma(),k;k=f;var m=k.M();pC(m)&&(m=m.childNodes[k.ma()]||m);var m=qC(m),q=k.ba();pC(q)&&(q=q.childNodes[k.Ba()]||q);q=qC(q);k=m==q;if(m=!k)a:{var q=f,m=q.ba(),q=q.Ba(),s=m;if(pC(s)){var x=s.childNodes[q];if(!x||1==x.nodeType&&pC(x)){m=l;break a}}for(x=qC(s);x!=
s;){if(DC(s)){m=i;break a}s=s.parentNode}m=q!=is(m)}f.Ic();(f=aD(c,b))?f=Dr(f,d):(f=Dr(b,b.childNodes.length),g=l);f.select();k&&(k=qC(f.M()),CC(k,i)&&(g="&nbsp;",tb&&"LI"==k.tagName&&(g="<br>"),k.innerHTML=g,ks(k.firstChild),g=l));m&&(f=qC(f.M()),k=DC(f),f&&k&&(jc(f,k.childNodes),L(k)));g&&(f=Dr(aD(c,b),d),f.select())}}}return nC(a,i)};function gD(){}var hD=new gD,iD=["click",A?"keypress":"keydown"];gD.prototype.c=function(a,b,c,d,f){function g(a){if("click"==a.type&&gd(a))b.call(d,a);else if(13==a.keyCode||3==a.keyCode)a.type="keypress",b.call(d,a)}g.xj=b;g.oS=d;f?f.c(a,iD,g):N(a,iD,g)};gD.prototype.ya=function(a,b,c,d,f){for(var g=0;c=iD[g];g++){var k;k=rd(a,c,l)||[];for(var m,q=0;m=k[q];q++)if(m.Rf.xj==b&&m.Rf.oS==d){f?f.ya(a,c,m.Rf):qd(a,c,m.Rf);break}}};function jD(a){M.call(this);this.qk=a||window;this.Tr=N(this.qk,"resize",this.sw,l,this);this.ec=$b(this.qk);if(B&&nb||tb&&this.qk.self!=this.qk.top)this.Et=window.setInterval(u(this.qB,this),kD)}w(jD,zd);var kD=500;r=jD.prototype;r.Tr=j;r.qk=j;r.ec=j;r.Et=j;r.hl=function(){return this.ec?this.ec.clone():j};r.m=function(){jD.g.m.call(this);this.Tr&&(sd(this.Tr),this.Tr=j);this.Et&&(window.clearInterval(this.Et),this.Et=j);this.ec=this.qk=j};r.sw=function(){this.qB()};
r.qB=function(){var a=$b(this.qk);Rb(a,this.ec)||(this.ec=a,this.dispatchEvent("resize"))};function lD(a,b){M.call(this);this.W=Sb(a);this.G=new me(this);this.aA=new jD(this.W.Ja());this.ad={};this.md=this.W.j("DIV",{className:mD});S(this.md,l);a.appendChild(this.md);Rf(this.md,"zIndex",b);this.Qm=this.md;this.oK=this.W.j("DIV",{className:"tr_bubble_closebox",innerHTML:"&nbsp;"});this.Qm.appendChild(this.oK);AC(this.md,this.G);this.di=new Yk(this.md)}w(lD,zd);var mD="tr_bubble";r=lD.prototype;r.Ob=le("goog.ui.editor.Bubble");
r.m=function(){lD.g.m.call(this);L(this.md);this.md=j;this.G.w();this.G=j;this.aA.w();this.aA=j};r.R=n("Qm");r.Db=n("md");r.qN=function(){this.H()&&this.xa()};r.YM=function(){for(var a in this.ad)L(this.ad[a].element);this.ad={};E.remove(this.md,"tr_multi_bubble");this.G.Ac();this.dispatchEvent("hide")};r.H=function(){return this.di.H()};var nD=z?4:2,oD=new Nf(nD,0,nD,0);
lD.prototype.xa=function(){var a=j,b=i,c;for(c in this.ad)var d=this.ad[c],a=d.Fz,b=b&&d.xR;c=496;a=gg(this.md)!=gg(a);b&&(c=pD(this,a?7:5,4,9));c&496&&(c=pD(this,a?6:4,5,9));c&496&&(c=pD(this,a?7:5,4,5),c&496&&this.Ob.nk("reposition(): positionAtAnchor() failed with "+c))};function pD(a,b,c,d){var f=j,g;for(g in a.ad){var k=a.ad[g].Fz;if(!f||uc(k,f))f=a.ad[g].Fz}return xi(f,b,a.md,c,j,oD,d)}
function qD(a,b,c,d,f,g){this.type=c;this.Fz=f;this.xR=g;this.element=a.j("DIV",{className:"tr_bubble_panel",id:b},a.j("DIV",{className:"tr_bubble_panel_title"},d+":"),a.j("DIV",{className:"tr_bubble_panel_content"}))}qD.prototype.R=function(){return this.element.lastChild};function rD(){Ds.call(this);this.Xb=new me(this)}w(rD,Ds);function sD(a,b){return new lD(a,b)}var tD={};r=rD.prototype;r.Jj=j;r.jx=l;r.Wc=mf("AbstractBubblePlugin");r.Yq=function(){this.H()&&this.gj();return l};
r.gj=function(a,b){var c;if(a)c=a.target;else if(b)c=b;else{var d=ft(this.o);if(d){var f=d.M(),g=d.ba(),k=d.ma(),m=d.Ba();z&&(d.isCollapsed()&&f!=g)&&(d=Dr(f,k));1==f.nodeType&&(f==g&&k==m-1)&&(f=f.childNodes[k],1==f.nodeType&&(c=f))}c=c||d&&d.Db()}var q;a:{if(c&&(k=this.SL(c))){if(k!=this.kt||!this.Jj){uD(this);this.Rg&&em(this.Rg);c=vD(this);var s=this.Mv();if(!F.some(c.ad,function(a){return a.type==s})){this.kt=k;var f=this.Mv(),m=this.RC(),g=u(this.FK,this),x=this.LS(),d=fb(),k=new qD(c.W,d,f,
m,k,!x);c.ad[d]=k;m=0;for(x=c.Qm.childNodes.length-1;m<x;m++){var C=c.Qm.childNodes[m];if(c.ad[C.id].type>f){q=C;break}}lc(k.element,q||c.Qm.lastChild);g(k.R());AC(k.element,c.G);q=F.Ha(c.ad);1==q?(c.G.c(c.aA,"resize",c.qN).c(c.di,"hide",c.YM),c.di.n(i),c.xa()):2==q&&E.add(c.md,"tr_multi_bubble");c.xa();this.Jj=d;this.Xb.c(c,"hide",this.lD);this.$h();this.jx&&this.Xb.c(c.R(),"keydown",this.HP);this.Xb.c(c.R(),"mouseover",function(){this.Rg&&this.Rg.stop()},this)}}else this.Rg&&this.Rg.stop();q=l;
break a}uD(this);q=l}return q};r.disable=function(a){if(a.yj==Rs){var b=tD[a.id];b&&(b.w(),delete tD[a.id])}};function vD(a){var b=a.dX||a.o.Dk.document.body;a.W=Sb(b);var c=tD[a.o.id];c||(c=sD.call(j,b,a.o.PJ||0),tD[a.o.id]=c);return c}r.Mv=p("");r.RC=p("");r.LS=nf;
function uD(a){if(a.Jj&&(!a.Rg||!a.Rg.wb()))a.Rg=new dm(function(){if(this.Jj){var a=vD(this),c=this.Jj;L(a.ad[c].element);delete a.ad[c];c=F.Ha(a.ad);1>=c&&E.remove(a.md,"tr_multi_bubble");0==c?a.di.n(l):a.xa();this.lD()}},250,a),a.Rg.start()}r.$h=ia;r.lD=function(){this.Jj=this.kt=j;this.Xb.Ac()};r.ow=function(a){if(this.jx&&this.H()&&9==a.keyCode&&!a.shiftKey){var b=vD(this).R();if(b=I("tr_bubble_link",b))return b.focus(),a.preventDefault(),i}return l};
r.HP=function(a){if(this.H()&&9==a.keyCode){var b=vD(this).R(),b=Xb("tr_bubble_link",b);if(a.shiftKey?b[0]==a.target:b.length&&b[b.length-1]==a.target)this.o.focus(),a.preventDefault()}};r.H=function(){return!!this.Jj};r.xa=function(){var a=vD(this);a&&a.xa()};
r.iq=function(a,b,c,d,f){b=this.W.j("SPAN",{className:"tr_bubble_link"},f?this.W.j("I",{className:f},b):b);this.jx&&b.setAttribute("tabindex",0);b.setAttribute("role","link");d?d.appendChild(b):(d=this.W.f(a))&&oc(b,d);b.id=a;AC(b,this.Xb);c&&(a=this.Xb,hD.c(b,c,h,a.oa||a,a));return b};v("Go to link: ");v("Change");v("Remove");function wD(a){M.call(this);this.Uc=a}w(wD,zd);wD.prototype.show=function(){this.Re||(this.Re=this.Vu(),this.Re.addEventListener(ll,this.cM,l,this));this.Re.n(i)};wD.prototype.hide=function(){this.Re&&this.Re.n(l)};wD.prototype.jb=function(){return!!this.Re&&this.Re.H()};function xD(a){this.Sk=a;this.ti=new cl("",i,this.Sk.Uc);this.Sm=new jl(this.Sk.Uc);this.Rm={};this.oh("tr-dialog")}xD.prototype.Ma=function(a){this.ti.Ma(a);return this};
function yD(a,b){var c=v("OK");a.Sm.set("ok",b||c,i);a.Rm.ok=u(a.Sk.UM,a.Sk)}function zD(a){var b=ql,c=v("取消");a.Sm.set(b,c,l,i);a.Rm[b]=u(a.Sk.dw,a.Sk);return a}xD.prototype.je=function(a,b,c){c=c||fb();this.Sm.set(c,a);this.Rm[c]=b;return this};xD.prototype.oh=function(a){E.add(el(this.ti),a);return this};xD.prototype.Fa=function(a){this.ti.R().appendChild(a);return this};
function AD(a){a.Sm.xb()&&(yD(a),zD(a));nl(a.ti,a.Sm);var b=a.Rm;a.Rm=j;a.ti.addEventListener(ol,function(a){if(b[a.key])return b[a.key](a)});gl(a.ti,i);var c=a.ti;a.ti=j;return c}r=wD.prototype;r.Nv=function(a){return this.Re.jc.Kf(a)};r.UM=function(a){return(a=this.an(a))?this.dispatchEvent(a):l};r.dw=function(){return this.dispatchEvent("cancel")};r.m=function(){this.Re&&(this.hide(),this.Re.w(),this.Re=j);wD.g.m.call(this)};r.cM=function(){this.dispatchEvent("afterhide")};function BD(a){Ds.call(this);this.vK=a}w(BD,Ds);r=BD.prototype;r.De=function(a){return a==this.vK};r.execCommand=function(a,b){return this.Ve.apply(this,arguments)};r.Ve=function(a,b){this.uG||CD(this);this.kc||(this.kc=this.Uu(Sb(this.o.Dk),b));var c=ft(this.o);this.My=c&&new uC(c);Er(this.o.Ya.Ja());pd(this.kc,"afterhide",this.zn,l,this);this.o.Fg=i;this.kc.show();this.dispatchEvent("dialogOpened");Hs(this.o);return i};
r.zn=function(){this.o.Fg=l;DD(this);this.uG||CD(this);this.dispatchEvent("dialogClosed");Hs(this.o);this.o.oq.selectionchange=Aa()};function DD(a){a.My&&(a.My.restore(),a.My=j);a.o.focus()}r.m=function(){CD(this);BD.g.m.call(this)};r.uG=l;r.cx=l;function CD(a){a.kc&&!a.cx&&(a.cx=i,a.kc.w(),a.kc=j,a.cx=l)};function ED(){}w(ED,RB);ja(ED);ED.prototype.C=p("goog-link-button");ch("goog-link-button",function(){return new Kh(j,ED.v())});function FD(){Ds.call(this)}w(FD,Ds);FD.prototype.Zq=function(a){if(A&&this.o.Fg)a=l;else if(9==a.keyCode&&!a.metaKey&&!a.ctrlKey){var b=ft(this.o);Jc(b.Db(),"LI")||O.some(b,function(a){return"LI"==a.tagName})?(this.o.execCommand(a.shiftKey?"+outdent":"+indent"),a.preventDefault(),a=i):a=l}else a=l;return a};function GD(){Ds.call(this)}w(GD,FD);GD.prototype.Wc=p("ListTabHandler");function HD(a){Ds.call(this);this.eP=a}w(HD,Ds);r=HD.prototype;r.Wc=mf("LoremIpsum");r.yp=of;r.ip=l;r.queryCommandValue=function(a){return"usinglorem"==a&&this.ip};
r.execCommand=function(a,b){if("clearlorem"==a){var c=!!b,d=this.o;if(this.ip&&!d.Fg){var f=d.f();f||(f=d.yc);this.ip=l;f.style.fontStyle=this.vP;d.be(i,j,i);c&&d.wd()&&(B?(Ub(d.f()).body.focus(),d.Jf()):tb&&kt(d))}}else"updatelorem"==a&&(c=this.o,!this.ip&&(!c.Fg&&Ss!=c.id)&&((d=c.f())||(d=c.yc),CC(d)&&(this.ip=i,this.vP=d.style.fontStyle,d.style.fontStyle="italic",c.be(i,this.eP,i))))};r.De=function(a){return"clearlorem"==a||"updatelorem"==a||"usinglorem"==a};function ID(){Ds.call(this);this.ZQ=j}w(ID,Ds);var JD=/^(DIV|TR|LI|BLOCKQUOTE|H\d|PRE|XMP)/;function KD(a){a.push("<br>")}r=ID.prototype;r.Wc=p("RemoveFormatting");r.De=function(a){return"+removeFormat"==a};r.Ve=function(a){"+removeFormat"==a&&!ft(this.o).isCollapsed()&&(a=this.ZQ||u(this.jG,this),LD(this,a),iC(this).va().execCommand("RemoveFormat",l,h),Ur&&LD(this,function(a){var c=D("528")?/&nbsp;/g:/\u00A0/g;return a.replace(c," ")}))};
r.Zq=function(a,b,c){return!c?l:" "==b?(this.o.execCommand("+removeFormat"),i):l};function MD(a,b){for(var c=a.o.f();b&&b!=c;){if("TABLE"==b.tagName)return b;b=b.parentNode}return j}
function LD(a,b){var c=ft(a.o);if(!(1<c.aj())){if(A){var d=zC(c,a.o.f()),f=MD(a,d.M()),g=MD(a,d.ba());if(f||g){if(f==g)return;var k,m=c;k=f;var c=g,d=new uC(m),q=m.M(),s=m.ma(),x=m.ba(),m=m.Ba(),C=iC(a);if(k){var J=C.createTextNode("");mc(J,k);q=J;s=0}c&&(J=C.createTextNode(""),lc(J,c),x=J,m=0);mr(q,s,x,m).select();k=d;f||(c=L(eC(k,i)),a.tz=c);g||(c=L(eC(k,l)),a.uv=c);c=ft(a.o);d=zC(c,a.o.f())}d.select();c=d}q=c;c=iC(a).j("div");d=q.Qd();Hr?c.appendChild(d.cloneContents()):Gr&&(s=q.Ze(),s=s.replace(/\r\n/g,
"\r"),x=s.length,q=x-s.replace(/^[\s\xa0]+/,"").length,s=x-Pa(s).length,d.moveStart("character",q),d.moveEnd("character",-s),q=d.htmlText,"Formatted"==d.queryCommandValue("formatBlock")&&(q=Qa(d.htmlText)),c.innerHTML=q);q=b(c.innerHTML);C=ft(a.o);c=iC(a);s=fb();d=fb();q='<span id="'+s+'"></span>'+q+'<span id="'+d+'"></span>';m=fb();x='<span id="'+m+'"></span>';if(Gr){J=C.ue(0).Qd();J.pasteHTML(x);for(var G;(G=J.parentElement())&&CC(G)&&!sC(G);){C=G.nodeName;if("TD"==C||"TR"==C||"TH"==C)break;L(G)}J.pasteHTML(q);
(m=c.f(m))&&L(m)}else if(Hr){c.va().execCommand("insertImage",l,m);C=RegExp("<[^<]*"+m+"[^>]*>");G=ft(a.o).Db();3==G.nodeType&&(G=G.parentNode);for(;!C.test(G.innerHTML);)G=G.parentNode;if(A)G.innerHTML=G.innerHTML.replace(C,q);else{G.innerHTML=G.innerHTML.replace(C,x);for(G=m=c.f(m);(G=m.parentNode)&&CC(G)&&!sC(G);){C=G.nodeName;if("TD"==C||"TR"==C||"TH"==C)break;mc(m,G);L(G)}G.innerHTML=G.innerHTML.replace(RegExp(x,"i"),q)}}G=c.f(s);c=c.f(d);mr(G,0,c,c.childNodes.length).select();L(G);L(c);A&&k&&
(c=ft(a.o),G=a.o.f(),a.tz&&(G.insertBefore(a.tz,G.firstChild),a.tz=j),a.uv&&(G.appendChild(a.uv),a.uv=j),G=j,d=eC(k,i),q=eC(k,l),d&&q&&(G=mr(d,0,q,0)),kC((f?G:c).M(),(f?G:c).ma(),(g?G:c).ba(),(g?G:c).Ba()).select(),k.w())}}
r.jG=function(a){var b=document.createElement("div");b.innerHTML=a;for(var a=[],b=[b.childNodes,0],c=[],d=0,f=[],g=0,k=0;0<=k;k-=2){for(var m=l;0<g&&k<=f[g-1];)g--,m=i;m&&KD(a);for(m=l;0<d&&k<=c[d-1];)d--,m=i;m&&KD(a);for(var m=b[k],q=b[k+1];q<m.length;){var s=m[q++],x=s.nodeName;switch(x){case "#text":s=0<d?s.nodeValue:La(s.nodeValue);s=Ra(s);a.push(s);continue;case "P":KD(a);KD(a);break;case "BR":KD(a);continue;case "TABLE":KD(a);f[g++]=k;break;case "PRE":case "XMP":c[d++]=k;break;case "STYLE":case "SCRIPT":case "SELECT":continue;
case "A":if(s.href&&""!=s.href){a.push("<a href='");a.push(s.href);a.push("'>");a.push(this.jG(s.innerHTML));a.push("</a>");continue}else break;case "IMG":a.push("<img src='");a.push(s.src);a.push("'");"0"==s.border&&a.push(" border='0'");a.push(">");continue;case "TD":s.previousSibling&&a.push(" ");break;case "TR":s.previousSibling&&KD(a);break;case "DIV":var C=s.parentNode;if(C.firstChild==s&&JD.test(C.tagName))break;default:JD.test(x)&&KD(a)}s=s.childNodes;0<s.length&&(b[k++]=m,b[k++]=q,m=s,q=
0)}}return a.join("").replace(/\xa0|[ \t]+/g," ")};function ND(a){this.YA=a}w(ND,zd);function PD(){M.call(this);this.XO=100;this.Dd=[];this.Pj=[];this.qs=[]}w(PD,zd);r=PD.prototype;r.or=j;r.Rz=function(){QD(this,this.Dd,this.Pj)};r.xy=function(){QD(this,this.Pj,this.Dd)};function QD(a,b,c){if(b.length){var d=b.pop();c.push(d);a.qs.push({type:b==a.Dd?"before_undo":"before_redo",PC:b==a.Dd?d.Rz:d.xy,state:d});1==a.qs.length&&a.yg();(0==b.length||1==c.length)&&a.dispatchEvent("state_change")}}
r.yg=function(){if(!(this.or||0==this.qs.length)){var a=this.qs.shift();this.dispatchEvent({type:a.type,state:a.state})&&(a.state.YA?(this.or=N(a.state,"action_completed",this.CL,l,this),a.PC.call(a.state)):(a.PC.call(a.state),this.yg()))}};r.CL=function(){sd(this.or);this.or=j;this.yg()};function RD(a){Ds.call(this);a=a||new PD;this.IE&&sd(this.IE);this.de=a;this.IE=N(this.de,"state_change",this.gL,l,this);this.Vi={};this.gn={};this.OD=j;this.SJ=u(this.gS,this)}w(RD,Ds);RD.prototype.Ob=le("goog.editor.plugins.UndoRedo");RD.prototype.Hn=j;var SD=F.im({JW:"+undo",$V:"+redo"});r=RD.prototype;r.De=function(a){return a in SD};r.FH=function(a){this.disable(a);this.o=j};
r.enable=function(a){if(!this.isEnabled(a)){gt(a);var b=new me(this);A||b.c(a,"beforechange",this.eM);b.c(a,Ns,this.lM);b.c(a,"blur",this.cw);this.Vi[a.Eg]=b;TD(this,a)}};r.disable=function(a){gt(a);var b=this.Vi[a.Eg];b&&(b.w(),delete this.Vi[a.Eg]);this.gn[a.Eg]&&delete this.gn[a.Eg]};r.isEnabled=function(a){return!!this.Vi[a.Eg]};r.m=function(){RD.g.m.call(this);for(var a in this.Vi)this.Vi[a].w(),delete this.Vi[a];this.o=j;this.de&&(this.de.w(),delete this.de)};r.Wc=p("UndoRedo");
r.execCommand=function(a){"+undo"==a?this.de.Rz():"+redo"==a&&this.de.xy()};r.queryCommandValue=function(a){var b=j;"+undo"==a?b=0<this.de.Dd.length:"+redo"==a&&(b=0<this.de.Pj.length);return b};r.gL=function(){this.o.dispatchEvent({type:"cvc",wK:["+redo","+undo"]})};
r.gS=function(a,b,c){var d=this.o;if(d){Gs(d,i,i);try{d.yh();d.execCommand("clearlorem",i);d.f().innerHTML=b;c&&c.select();var f=this.o;d.focus();f&&f.Eg!=a.qn&&f.execCommand("updatelorem");var g=this.gn[a.qn];g.ni=b;g.DH=c}catch(k){this.Ob.log(ce,"Error while restoring undo state",k)}finally{this.Hn=a,d.Se(),Hs(d)}}};
r.Zq=function(a,b,c){if(c){var d;"z"==b?d=a.shiftKey?"+redo":"+undo":"y"==b&&(d="+redo");if(d)return(a="+undo"==d?this.de.Dd[this.de.Dd.length-1]:this.de.Pj[this.de.Pj.length-1])&&a.qn?this.o.execCommand(d):this.execCommand(d),i}return l};r.eM=function(a){if(!this.Hn){var a=a.target,b=a.Eg;this.OD!=b&&(this.OD=b,TD(this,a))}};r.lM=function(a){this.Hn?(a=this.Hn,this.Hn=j,a.dispatchEvent("action_completed")):TD(this,a.target)};r.cw=function(a){(a=a.target)&&gt(a)};
function TD(a,b){var c=b.Eg,d,f;b.queryCommandValue("usinglorem")?(d="",f=j):(d=b.f().innerHTML,f=new UD(b),f=!f.Jg()?j:f);var g=a.gn[c];if(g){if(g.ni==d)return;if(""==d||""==g.ni){var k=b.Cs(8,"",{});if(d==k&&""==g.ni||g.ni==k&&""==d)return}g.yy=d;g.KR=f;k=a.de;if(0==k.Dd.length||!g.Ti(k.Dd[k.Dd.length-1])){k.Dd.push(g);k.Dd.length>k.XO&&k.Dd.shift();var m=k.Pj.length;k.Pj.length=0;k.dispatchEvent({type:"state_added",state:g});(1==k.Dd.length||m)&&k.dispatchEvent("state_change")}}a.gn[c]=new VD(c,
d,f,a.SJ)}function VD(a,b,c,d){this.YA=i;this.qn=a;this.sG=d;this.ni=b;this.DH=c}w(VD,ND);VD.prototype.Rz=function(){this.sG(this,this.ni,this.DH)};VD.prototype.xy=function(){this.sG(this,this.yy,this.KR)};VD.prototype.Ti=function(a){return this.qn==a.qn&&this.ni==a.ni&&this.yy==a.yy};
function UD(a){this.Md=a;var b=a.Ya.Ja(),a=(a=ft(a))&&a.Pf()&&a.Ja()==b?a:j;if(Hr){if(b=a,this.Er=l,b){var c=Mq(b),d=Nq(b);if(c&&d){var a=b.Sh()?b.Ba():b.ma(),c=new $C(c,this.Md.f()),f=Oq(b),d=new $C(d,this.Md.f());b.Sh()?(this.ta=d,this.uz=f,this.sa=c,this.vv=a):(this.ta=c,this.uz=a,this.sa=d,this.vv=f);this.Er=i}}}else Gr&&(b=a,this.Er=l,b&&(a=b.ue(0).Qd(),uc(this.Md.f(),a.parentElement())&&(b=this.Md.Ya.va().body.createTextRange(),b.moveToElementText(this.Md.f()),d=a.duplicate(),d.collapse(i),
d.setEndPoint("StartToStart",b),this.ta=WD(d),a=a.duplicate(),a.setEndPoint("StartToStart",b),this.sa=WD(a),this.Er=i)))}UD.prototype.Jg=n("Er");UD.prototype.toString=function(){return Hr?"W3C:"+this.ta.toString()+"\n"+this.uz+":"+this.sa.toString()+"\n"+this.vv:"IE:"+this.ta+","+this.sa};UD.prototype.select=function(){var a=this.se(this.Md.f());a&&(Gr&&this.Md.f().focus(),Cr(a).select())};
UD.prototype.se=function(a){if(Hr){var b=aD(this.ta,a),a=aD(this.sa,a);return!b||!a?j:mr(b,this.uz,a,this.vv).Qd()}b=a.ownerDocument.body.createTextRange();b.moveToElementText(a);b.collapse(i);b.moveEnd("character",this.sa);b.moveStart("character",this.ta);return b};
function WD(a){var b=a.duplicate(),c=a.text,d=c.length;b.collapse(i);b.moveEnd("character",d);for(var f,g=10;(f=b.compareEndPoints("EndToEnd",a))&&!(d-=f,b.moveEnd("character",-f),--g,0==g););a=0;for(b=c.indexOf("\n\r");-1!=b;)++a,b=c.indexOf("\n\r",b+1);return d+a};function XD(a,b){mh.call(this,a||Gh.v(),b)}w(XD,mh);ch("goog-toolbar-separator",function(){return new XD});function YD(a,b){M.call(this);this.oa=new me(this);this.Md=a;this.rb=b;this.uy=[];Kg(this.rb,function(a){a.Va&&this.uy.push(ZD(a.Sd()))},this);this.rb.Ie(l);this.oa.c(this.Md,"cvc",this.$T).c(this.rb,"action",this.aw)}w(YD,zd);function ZD(a){return a}r=YD.prototype;r.e=n("oa");r.Rd=n("Md");r.H=function(){return this.rb.H()};r.n=function(a){this.rb.n(a)};r.isEnabled=function(){return this.rb.isEnabled()};r.Pa=function(a){this.rb.Pa(a)};r.blur=function(){this.rb.Xc(j)};
r.m=function(){YD.g.m.call(this);this.oa&&(this.oa.w(),delete this.oa);this.rb&&(this.rb.w(),delete this.rb);delete this.Md;delete this.uy};r.$T=function(a){if(this.rb.isEnabled()&&this.dispatchEvent("change")){var b;try{b=this.Md.queryCommandValue(a.wK||this.uy)}catch(c){b={}}var a=b,d;for(d in a)if(b=Jg(this.rb,d)){var f=a[d];b.oi?b.oi(f):b.Jc(!!f)}}};r.aw=function(a){var b=a.target.Sd();this.Md.execCommand(b,a.target.O())};function $D(a){this.tL=a}w($D,ad);$D.prototype.type="ok";function aE(a){ad.call(this,"change");this.Jg=a}w(aE,ad);function bE(a){return!a?"":"//www.zhihu.com/equation?tex="+encodeURIComponent(a)};function cE(a){T.call(this,a)}w(cE,T);cE.prototype.hj="";cE.prototype.n=function(a){S(this.f(),a)};function dE(a,b,c,d,f,g,k,m){this.mi=b;this.mh=k||[];for(var b=m||eE.v(),m=[],c=-c,d=-d,q=0;q<k.length;q++)m.push(K("DIV",{"class":b.C()+"-item",style:"width:"+f+"px;height:"+g+"px;background-position:"+c+"px "+d+"px;"})),c-=f;this.Wf=a;oi.call(this,m,b)}w(dE,oi);dE.prototype.Mh=n("mi");dE.prototype.Nf=function(a){dE.g.Nf.call(this,a);this.Wf.dispatchEvent(new fE(gE,this))};dE.prototype.Nh=function(a){dE.g.Nh.call(this,a);a.relatedTarget&&!uc(this.f(),a.relatedTarget)&&this.Wf.bv()};
dE.prototype.Yc=function(a){dE.g.Yc.call(this,a);a.relatedTarget&&!uc(this.f(),a.relatedTarget)&&this.Wf.cv.stop()};function fE(a,b,c){ad.call(this,a,c);this.hR=b}var gE="a";fE.prototype.Vv=n("hR");function eE(){}w(eE,gi);ja(eE);eE.prototype.C=p("ee-palette");function hE(a){dE.call(this,a,"a",0,150,18,18,"\\leftarrow \\rightarrow \\leftrightarrow \\Leftarrow \\Rightarrow \\Leftrightarrow \\uparrow \\downarrow \\updownarrow \\Uparrow \\Downarrow \\Updownarrow".split(" "));si(this,new Qb(12,1))}w(hE,dE);function iE(a){dE.call(this,a,"c",0,70,18,18,"\\leq \\geq \\prec \\succ \\preceq \\succeq \\ll \\gg \\equiv \\sim \\simeq \\asymp \\approx \\ne \\subset \\supset \\subseteq \\supseteq \\in \\ni \\notin".split(" "));si(this,new Qb(7,3))}w(iE,dE);function jE(a){dE.call(this,a,"g",0,30,18,18,"\\alpha \\beta \\gamma \\delta \\epsilon \\varepsilon \\zeta \\eta \\theta \\vartheta \\iota \\kappa \\lambda \\mu \\nu \\xi \\pi \\varpi \\rho \\varrho \\sigma \\varsigma \\tau \\upsilon \\phi \\varphi \\chi \\psi \\omega \\Gamma \\Delta \\Theta \\Lambda \\Xi \\Pi \\Sigma \\Upsilon \\Phi \\Psi \\Omega".split(" "));si(this,new Qb(7,6))}w(jE,dE);function kE(a){dE.call(this,a,"m",0,90,30,56,"x_{a};x^{b};x_{a}^{b};\\bar{x};\\tilde{x};\\frac{a}{b};\\sqrt{x};\\sqrt[n]{x};\\bigcap_{a}^{b};\\bigcup_{a}^{b};\\prod_{a}^{b};\\coprod_{a}^{b};\\left( x \\right);\\left[ x \\right];\\left{ x \\right};\\left| x \\right|;\\int_{a}^{b};\\oint_{a}^{b};\\sum_{a}^{b}{x};\\lim_{a \\rightarrow b}{x}".split(";"));si(this,new Qb(10,2))}w(kE,dE);function lE(a){dE.call(this,a,"mn",0,0,46,18,["g","s","c","m","a"],mE.v());si(this,new Qb(5,1))}w(lE,dE);lE.prototype.n=function(a,b){return lE.g.n.call(this,i,b)};function mE(){}w(mE,eE);ja(mE);mE.prototype.C=p("ee-menu-palette");function nE(a){dE.call(this,a,"s",0,50,18,18,"\\times \\div \\cdot \\pm \\mp \\ast \\star \\circ \\bullet \\oplus \\ominus \\oslash \\otimes \\odot \\dagger \\ddagger \\vee \\wedge \\cap \\cup \\aleph \\Re \\Im \\top \\bot \\infty \\partial \\forall \\exists \\neg \\angle \\triangle \\diamond".split(" "));si(this,new Qb(7,5))}w(nE,dE);function oE(){M.call(this);this.NF={};this.ym=j;this.G=new me(this);this.cv=new Id(300);this.G.c(this.cv,Kd,this.bD)}w(oE,zd);r=oE.prototype;r.Vv=function(a){var b=this.NF,c=b[a];if(!c){switch(a){case "mn":c=new lE(this);break;case "g":c=new jE(this);break;case "s":c=new nE(this);break;case "c":c=new iE(this);break;case "m":c=new kE(this);break;case "a":c=new hE(this);break;default:e(Error("Invalid palette type!"))}b[a]=c}return c};
r.setActive=function(a){var b=this.ym;b&&b.n(l);this.ym=b=this.Vv(a);b.n(i);return b};r.bv=function(){this.cv.start()};r.bD=function(){this.setActive("mn")};r.m=function(){oE.g.m.call(this);this.NF=this.ym=j};function pE(a,b,c){T.call(this,c);this.hj=b;this.Wf=a.gR}w(pE,cE);r=pE.prototype;r.qE="";r.Hu=0;
r.j=function(){var a=v("TeX 公式"),b=v("预览"),c=v("Learn more"),d=this.W,c=d.j("DIV",{style:"display: none;"},d.j("SPAN",{"class":"ee-section-title ee-section-title-floating"},a),this.hj?d.j("A",{id:"ee-section-learn-more",target:"_blank",href:this.hj},c):j,d.j("DIV",{style:"clear: both;"}),a=this.ZN=d.j("DIV",{style:"position: relative"}));this.Wf.setActive("mn").N(a);a.appendChild(d.j("DIV",{style:"clear:both"}));var f=this.ah=d.j("textarea",{"class":"ee-tex",dir:"ltr"});a.appendChild(f);a.appendChild(d.j("DIV",
{"class":"ee-section-title"},b));b=this.zR=d.j("DIV",{"class":"ee-preview-container"});a.appendChild(b);this.d=c};r.p=function(){this.iH=new zw(this.ah);N(this.iH,"input",this.oD,l,this);this.e().c(this.ah,"keydown",this.oD);this.e().c(this.Wf,gE,this.XM,l,this)};r.n=function(a){pE.g.n.call(this,a);a&&Ld(this.HL,0,this)};r.HL=function(){this.ah.focus();np(this.ah,this.ah.value.length)};
function qE(a){var b=a.cl();if(b!=a.qE){a.qE=b;var c=!(1024<b.length);a.dispatchEvent(new aE(c));var a=a.zR,d=Sb(a);d.Fs(a);b&&(c?b=d.j("IMG",{src:bE(b)}):(b=v("Equation is too long"),b=d.j("DIV",{"class":"ee-warning"},b)),d.appendChild(a,b))}}r.oD=function(){this.Hu++;Ld(u(this.lN,this,this.Hu),500)};r.lN=function(a){a==this.Hu&&qE(this)};
r.XM=function(a){var b=a.Vv(),c=this.Wf,d=c.ym,a=this.ah;if("mn"==b.Mh()){var f=b.ib,f=-1!=f?0<=f&&f<b.mh.length?b.mh[f]:j:j;if(d!=b&&d.Mh()==f){c.bD();return}f&&(b=this.Wf.setActive(f),b.f()||b.N(this.ZN),b=b.f(),Zf(b,0,-b.clientHeight))}else{d=this.Wf.ym;f=0<=d.ib&&d.ib<d.mh.length?d.mh[d.ib]:j;if(!f)return;Ld(u(this.hO,this,f+" "),0)}a.focus()};r.hO=function(a){var b=this.ah,c=kp(b),d=b.value,d=d.substring(0,c)+a+d.substring(c);b.value=d;np(b,c+a.length);qE(this)};r.cl=function(){return this.ah.value};
r.Uy=function(a){this.ah.value=a;qE(this)};r.m=function(){this.iH.w();this.Wf=j;pE.g.m.call(this)};function rE(a,b,c){T.call(this,c);this.EB=a;this.hj=b}w(rE,T);r=rE.prototype;r.bh=j;r.j=function(){rE.g.j.call(this);this.hq()};r.hq=function(){var a=this.f();this.bh=new pE(this.EB,this.hj,this.W);this.aa(this.bh);this.bh.N(a);this.bh.n(i)};r.Z=function(a){this.d=a;this.hq()};r.cl=function(){return this.bh.cl()};r.Uy=function(a){this.bh.Uy(a)};r.Rv=function(){var a=this.cl(),b=bE(a);return!b?"":'<img src="'+b+'" alt="'+Ra(a)+'" class="ee_img tr_noresize" eeimg="1" style="vertical-align: middle">'};
r.Jg=function(){return 1024<this.cl().length};r.n=function(a){this.bh.n(a)};r.m=function(){this.bh&&this.bh.w();this.EB=j;rE.g.m.call(this)};function sE(a,b,c,d){wD.call(this,b);this.Ui=new rE(a,d);this.Ui.N();this.Ui.Uy(c);this.Ui.addEventListener("+equation",this.mo,l,this)}w(sE,wD);sE.prototype.Vu=function(){var a=new xD(this),b=v("公式编辑器"),c=v("插入公式"),d=v("保存"),c=this.Ui.cl()?d:c;yD(zD(a.Ma(b).Fa(this.Ui.f())),c);return AD(a)};sE.prototype.an=function(){if(this.Ui.Jg())return j;var a=this.Ui.Rv();return new $D(a)};sE.prototype.mo=function(a){this.hF||(this.hF=this.Nv("ok"));this.hF.disabled=!a.Jg};function tE(a){this.hj=a||"";BD.call(this,"+equation")}w(tE,BD);r=tE.prototype;r.wa=le("goog.editor.plugins.EquationEditorPlugin");r.Wc=mf("EquationEditorPlugin");r.Uu=function(a,b){var c=b||j,d;c?(d=c.getAttribute("alt"),d||(d=c.getAttribute("src"),d=!d?"":decodeURIComponent(d.match(ve)[6]||j).slice(4)||"")):d="";this.MF=c;c={};c.gR=new oE;c=new sE(c,a,d,this.hj);c.addEventListener("ok",this.ej,l,this);return c};r.enable=function(a){tE.g.enable.call(this,a)};
r.disable=function(a){tE.g.disable.call(this,a)};r.ej=function(a){DD(this);this.o.yh();a=hc(iC(this).Aa,a.tL);if(this.MF)oc(a,this.MF);else{var b=ft(this.o);b.isCollapsed()||b.Ic();a=b.insertNode(a,l)}ls(a,l);this.o.Se()};function uE(){rD.call(this)}w(uE,rD);v("Equation:");var vE=v("Edit"),wE=v("Remove");r=uE.prototype;r.Wc=p("EquationBubble");r.SL=function(a){return a&&"IMG"==a.nodeName&&(a.getAttribute("eeimg")||E.has(a,"ee_img"))?a:j};r.FK=function(a){this.iq("ee_bubble_edit",vE,this.kL,a,"zg-icon zg-icon-pen");this.iq("ee_remove_remove",wE,this.RR,a,"zg-icon zg-icon-trash")};r.Mv=p("IMG");r.RC=function(){return v("Equation")};r.RR=function(){this.o.yh();L(this.kt);uD(this);this.o.Se()};
r.kL=function(){var a=this.kt;uD(this);this.o.execCommand("+equation",a)};function xE(a){Ds.call(this);this.Vz="http://upload."+Ak.Sl+":"+location.port+"/upload";F.extend(this.s={},this.V,a||{})}w(xE,Ds);r=xE.prototype;r.V={wY:ia};r.Wc=mf("FastUpload");
r.enable=function(a){if(!this.isEnabled(a)&&!(!window.URL&&!window.webkitURL||!window.FileReader||!window.FormData||!document.addEventListener)){$.fn.draghover=function(){return this.each(function(){var a=$(),b=$(this),c=i;b.on("dragenter",function(k){k=k.originalEvent;0===a.size()&&(c&&y.contains(k.dataTransfer.types,"Files"))&&b.trigger("draghoverstart",k);a=a.add(k.target)});b.on("dragleave",function(k){setTimeout(function(){a=a.not(k.target);0===a.size()&&c&&b.trigger("draghoverend",k)},1)});
b.on("dragstart",function(){c=l});b.on("drop dragend",function(){a=$();b.trigger("draghoverend");c=i})})};this.eA=$(this.o.f());var b=iC(this),c=$('<div class="editable-dropzone"><div class="row"><div class="cell"><div>拖拽至此处上传</div></div></div></div>');b.Ww(c[0],this.o.f());b=this.eI=c;new me(this);a.f().addEventListener("paste",u(this.rw,this));document.addEventListener("dragover",u(this.wM,this),l);b.on("dragover",u(this.vM,this));b.get(0).addEventListener("drop",u(this.Wq,this),l);$(window).draghover().on({draghoverstart:u(this.dD,
this),draghoverend:u(this.xM,this)});b.draghover().on({draghoverstart:u(this.pM,this),draghoverend:u(this.dD,this)})}};r.wM=function(a){y.contains(a.dataTransfer.types,"Files")&&(a.dataTransfer.dropEffect="none",a.preventDefault())};r.vM=function(a){a=a.originalEvent;a.dataTransfer.dropEffect="copy";a.preventDefault();a.stopPropagation()};r.dD=function(a){a.preventDefault();a.stopPropagation();yE(this,1)};r.pM=function(a){yE(this,2);a.stopPropagation()};
r.xM=function(a){a.preventDefault();yE(this,0)};function yE(a,b){var c=[{display:"none"},{display:"table",width:a.eA.width(),height:a.eA.height(),"background-color":"rgba(255, 255, 255, 0.5)"}];c[2]=$.extend({},c[1],{"background-color":"rgba(245, 245, 245, 0.5)"});a.eI.css(c[b])}r.rw=function(a){var b=this;a.clipboardData&&y.contains(a.clipboardData.types,"Files")&&y.forEach(a.clipboardData.items,function(c){-1<c.type.indexOf("image")&&(zE(b,c.getAsFile()),a.preventDefault())})};
r.Wq=function(a){var b=this;b.o.execCommand("clearlorem");var c=a.dataTransfer.files;document.createElement("img");a.preventDefault();var d=[];y.forEach(c,function(a){-1<a.type.indexOf("image")?(zE(b,a),d.push(i)):d.push(l)});y.every(d,function(a){return!a})&&X("文件类型不支持！");yE(b,0)};
function zE(a,b){var c=new FormData;c.append("via","xhr2");c.append("upload_file",b);var d;d=$.ajaxSettings.xhr();d.withCredentials=i;var f=$.ajax({url:a.Vz,data:c,processData:l,contentType:l,xhr:function(){return d},type:"POST"}).done(function(a){"string"===$.type(a)&&(a=JSON.parse(a));if(1===a.code)X(a.msg);else{var b=new Image;b.src=a.msg[0];b.setAttribute("originImgSrc",b.src.replace("_m.jpg","_r.jpg"));b.setAttribute("data-rawWidth",a.msg[1]);b.setAttribute("data-rawHeight",a.msg[2]);f.iA.after(b)}}).fail(function(){X("上传失败！>_<")}).always(function(){f.iA.remove()}),
c=f,g;g=iC(a);var k=g.j("IMG",{"class":"",style:"display:block",src:"/static/img/spinner2.gif"}),m=ft(a.o);!m||!yC(m)||!uc(a.o.f(),m.Db())?CC(a.o.field)?nc(a.o.f(),k):a.o.f().appendChild(k):m.Zf(k);z||(ls(k,l),g.Ja().focus());Gs(a.o);g=$(k);c.iA=g};var AE={};
function BE(a,b,c){function d(a){pc(a)}function f(b,c){for(;b!==a;){if(c(b))return b;b=b.parentNode}return j}function g(a){return a.tagName&&a.tagName===b}a||e("Missing Editable Container");b||(b="blockquote");var b=b.toUpperCase(),k=Ar();if(k&&CE(a,Mq(k))&&CE(a,Nq(k))){var m=kC(k.M(),k.ma(),k.ba(),k.Ba()),q;if(k.isCollapsed())q=[];else{var s=k.mc(),x=k.M(),C=k.ba();q=s.childNodes;var J=function(a){return x!==s&&!CE(a,x)},G=function(a){return!(a.previousSibling&&CE(a.previousSibling,C))};q=O.toArray(1===
q.length?q:O.Ez(O.jL(q,J),G))}var J=k.Db(),G=f(J,g),P=y.reduce(q,function(a,c){1===c.nodeType&&(g(c)?a.push(c):a.push.apply(a,y.toArray(c.getElementsByTagName(b))));return a},[]),W;if(G){if(c)return DE.Tt;pc(G)}else if(P.length){if(c)return DE.Tt;y.forEach(P,d)}else{if(c)return DE.rA;if(c=f(J,function(a){return y.contains(EE,a.tagName.toLowerCase())}))W=document.createElement(b),c.parentNode.insertBefore(W,c),W.appendChild(c);else if(k.M()!==k.ba())W=document.createElement(b),q[0].parentNode.insertBefore(W,
q[0]),y.forEach(q,function(a){W.appendChild(a)});else{m=b;FE.KI?document.execCommand("formatBlock",l,m):(c=Ar(),k=c.mc(),sa(k)&&1==k.nodeType&&CC(k)?(m=document.createElement(m),k===a?k.appendChild(m):oc(m,k),(B||A)&&m.appendChild(document.createElement("br")),ks(m)):(c=c.ba(),c=Kc(c,function(a){return BC(a.parentNode)||pC(a.parentNode)},i),k=O.Ez(new bs(c,i,i),rf(GE)),c=O.Ez(new bs(c,l,l),rf(GE)),k=O.toArray(k).reverse().concat(O.toArray(c)),k.length&&(m=document.createElement(m),c=y.Og(k),(q=c.nextSibling)&&
(q&&"BR"===q.tagName)&&L(q),mc(m,c),jc(m,k),(B||A)&&m.appendChild(document.createElement("br")),ls(m.lastChild))));return}}m&&(k=function(b,c){return b&&CE(a,b)&&is(b)>=c},k(m.M(),m.ma())&&k(m.ba(),m.Ba())&&m.select())}else if(c)return DE.rA}function GE(a){return a&&"BR"===a.tagName||BC(a)||pC(a)}function CE(a,b){return 3===a.nodeType?a===b:a.contains(3===b.nodeType?b.parentNode:b)}var EE=["ul","ol","dl","table"],DE={Tt:1,rA:0},FE=AE;FE.KI=!z;FE.toggle=BE;FE.Td=function(a,b){return BE(a,b,i)};
FE.GI=DE;function HE(){Ds.call(this)}w(HE,Ds);r=HE.prototype;r.Wc=mf("Blockquote");r.De=function(a){return"+blockquote"===a};r.Ve=function(a){this.De(a)&&AE.toggle(this.o.f())};r.queryCommandValue=function(){return AE.GI.Tt===AE.Td(this.o.f())};r.ow=function(a){if(13===a.keyCode)return this.iw(a)};r.fz=function(a,b){return IE(a,b).fz};
function IE(a,b){function c(a,b){return{fz:a,eF:b}}B&&(a.normalize(),b=Ar());var d,f=b;d=f.ba();var g=f.Ba(),f=f.mc(),k=f.childNodes.length;3!==d.nodeType&&k&&(d=f.childNodes[g===k?k-1:g]);if(!d)return c(l,j);if(CC(a))return c(i,a);for(g=d;g!==a;){if(DC(g))return c(l,j);g=g.parentNode}return d&&"BR"===d.tagName&&d.previousSibling&&"BR"===d.previousSibling.tagName?c(i,d):(d=b.Db())&&1===d.nodeType&&(!d.childNodes.length||CC(d))?c(i,d):c(l,j)}
r.iw=function(a){var b=ft(this.o);if(b.isCollapsed()){var c;a:{c=b.ba();for(var d=this.o.field;c!==d;){if("BLOCKQUOTE"===c.tagName)break a;c=c.parentNode}c=h}if(c&&(b=IE(c,b),b.fz)){a.preventDefault();a=document.createElement("div");mc(a,c);if(B||A)(c=(c=c.nextSibling)&&"BR"===c.tagName&&c)||(c=document.createElement("br")),a.appendChild(c);Dr(a,0).select();b.eF&&L(b.eF)}}};rk["+blockquote"]={Va:i,K:"引用内容",qa:"+blockquote",Da:"tr-icon tr-blockquote",factory:sj};function JE(a,b){this.Wa=a;this.Yz=!b}
JE.prototype.ei=function(a,b,c){var d,f=[];if(""!=a){d=bb(a);var g=RegExp("(^|\\W+)"+d,"i");O.some(this.Wa,function(a){String(a).match(g)&&f.push(a);return f.length>=b})}d=f;if(0==d.length&&this.Yz){var k=[];O.forEach(this.Wa,function(b,c){var d=a.toLowerCase(),f=String(b).toLowerCase(),g=0;if(-1!=f.indexOf(d))g=parseInt((f.indexOf(d)/4).toString(),10);else for(var m=d.split(""),P=-1,W=10,ma=0,Ha;Ha=m[ma];ma++)Ha=f.indexOf(Ha),Ha>P?(P=Ha-P-1,P>W-5&&(P=W-5),g+=P,P=Ha):(g+=W,W+=5);g<6*d.length&&k.push({gT:b,
zG:g,index:c})});k.sort(function(a,b){var c=a.zG-b.zG;return 0!=c?c:a.index-b.index});d=[];for(var m=0;m<b&&m<k.length;m++)d.push(k[m].gT)}c(a,d)};function KE(a){T.call(this);F.extend(this.s={},this.V,a||{});this.rc=j}w(KE,T);
var LE=[["ABAP",["abap"]],["ActionScript",["as","actionscript"]],["Ada",["ada","ada95ada2005"]],["ANTLR",["antlr"]],["ApacheConf",["apacheconf","aconf","apache"]],["AppleScript",["applescript"]],["AspectJ",["aspectj"]],["Asymptote",["asy","asymptote"]],["AutoHotkey",["ahk"]],["Awk",["awk","gawk","mawk","nawk"]],["BBCode",["bbcode"]],["Base Makefile",["basemake"]],["Bash",["bash","sh","ksh"]],["Batchfile",["bat"]],["Befunge",["befunge"]],["BlitzMax",["blitzmax","bmax"]],["Boo",["boo"]],["Brainfuck",
["brainfuck","bf"]],["Bro",["bro"]],["BUGS",["bugs","winbugs","openbugs"]],["C",["c"]],["CMake",["cmake"]],["c-objdump",["c-objdump"]],["aspx-cs",["aspx-cs"]],["C#",["csharp","c#"]],["Ceylon",["ceylon"]],["CFEngine3",["cfengine3","cf3"]],["Cheetah",["cheetah","spitfire"]],["Clojure",["clojure","clj"]],["CoffeeScript",["coffee-script","coffeescript"]],["Coldfusion HTML",["cfm"]],["cfstatement",["cfs"]],["Common Lisp",["common-lisp","cl"]],["Coq",["coq"]],["C++",["cpp","c++"]],["cpp-objdump",["cpp-objdump",
"c++-objdumb","cxx-objdump"]],["Croc",["croc"]],["CSS",["css"]],["CUDA",["cuda","cu"]],["Cython",["cython","pyx"]],["D",["d"]],["d-objdump",["d-objdump"]],["Darcs Patch",["dpatch"]],["Dart",["dart"]],["Delphi",["delphi","pas","pascal","objectpascal"]],["dg",["dg"]],["Diff",["diff","udiff"]],["Django/Jinja",["django","jinja"]],["DTD",["dtd"]],["Duel","duel;Duel Engine;Duel View;JBST;jbst;JsonML+BST".split(";")],["Dylan",["dylan"]],["ECL",["ecl"]],["eC",["ec"]],["Erlang",["erlang"]],["Elixir",["elixir",
"ex","exs"]],["ERB",["erb"]],["Evoque",["evoque"]],["FSharp",["fsharp"]],["Factor",["factor"]],["Fancy",["fancy","fy"]],["Fantom",["fan"]],["Felix",["felix","flx"]],["Fortran",["fortran"]],["GLSL",["glsl"]],["GAS",["gas"]],["Genshi",["genshi","kid","xml+genshi","xml+kid"]],["Gettext Catalog",["pot","po"]],["Gherkin",["Cucumber","cucumber","Gherkin","gherkin"]],["Gnuplot",["gnuplot"]],["Go",["go"]],["GoodData-CL",["gooddata-cl"]],["Gosu",["gosu"]],["Gosu Template",["gst"]],["Groff",["groff","nroff",
"man"]],["Groovy",["groovy"]],["Haml",["haml","HAML"]],["Haskell",["haskell","hs"]],["haXe",["hx","haXe"]],["HTML",["html"]],["HTTP",["http"]],["Hxml",["haxeml","hxml"]],["Hybris",["hybris","hy"]],["INI",["ini","cfg"]],["Io",["io"]],["Ioke",["ioke","ik"]],["IRC logs",["irc"]],["Jade",["jade","JADE"]],["JavaScript",["js","javascript"]],["JSON",["json"]],["Java",["java"]],["Java Server Page",["jsp"]],["Julia console",["jlcon"]],["Julia",["julia","jl"]],["Kconfig",["kconfig","menuconfig","linux-config",
"kernel-config"]],["Koka",["koka"]],["Kotlin",["kotlin"]],["Lasso",["lasso","lassoscript"]],["Lighttpd configuration file",["lighty","lighttpd"]],["Literate Haskell",["lhs","literate-haskell"]],["LiveScript",["live-script","livescript"]],["LLVM",["llvm"]],["Logtalk",["logtalk"]],["Lua",["lua"]],["MOOCode",["moocode"]],["Makefile",["make","makefile","mf","bsdmake"]],["Mako",["mako"]],["MAQL",["maql"]],["Mason",["mason"]],["Matlab",["matlab"]],["Matlab session",["matlabsession"]],["MiniD",["minid"]],
["Modelica",["modelica"]],["Modula-2",["modula2","m2"]],["MoinMoin/Trac Wiki markup",["trac-wiki","moin"]],["Monkey",["monkey"]],["MoonScript",["moon","moonscript"]],["Mscgen",["mscgen","msc"]],["MuPAD",["mupad"]],["MXML",["mxml"]],["MySQL",["mysql"]],["Myghty",["myghty"]],["NASM",["nasm"]],["Nemerle",["nemerle"]],["NewLisp",["newlisp"]],["Newspeak",["newspeak"]],["Nginx configuration file",["nginx"]],["Nimrod",["nimrod","nim"]],["NumPy",["numpy"]],["objdump",["objdump"]],["Objective-C",["objective-c",
"objectivec","obj-c","objc"]],["Objective-J",["objective-j","objectivej","obj-j","objj"]],["OCaml",["ocaml"]],["Octave",["octave"]],["Ooc",["ooc"]],["Opa",["opa"]],["OpenEdge ABL",["openedge","abl","progress"]],["Perl",["perl","pl"]],["PHP",["php","php3","php4","php5"]],["PL/pgSQL",["plpgsql"]],["PostScript",["postscript"]],["PostgreSQL console (psql)",["psql","postgresql-console","postgres-console"]],["PostgreSQL SQL dialect",["postgresql","postgres"]],["POVRay",["pov"]],["PowerShell",["powershell",
"posh","ps1"]],["Prolog",["prolog"]],["Properties",["properties"]],["Protocol Buffer",["protobuf"]],["Python",["python","py","sage"]],["Python Traceback",["pytb"]],["RConsole",["rconsole","rout"]],["Racket",["racket","rkt"]],["Embedded Ragel",["ragel-em"]],["Raw token data",["raw"]],["Rd",["rd"]],["REBOL",["rebol"]],["Redcode",["redcode"]],["RHTML",["rhtml","html+erb","html+ruby"]],["RobotFramework",["RobotFramework","robotframework"]],["reStructuredText",["rst","rest","restructuredtext"]],["Ruby",
["rb","ruby","duby"]],["Rust",["rust"]],["S",["splus","s","r"]],["Standard ML",["sml"]],["Sass",["sass","SASS"]],["Scala",["scala"]],["Scaml",["scaml","SCAML"]],["Scheme",["scheme","scm"]],["Scilab",["scilab"]],["SCSS",["scss"]],["Smali",["smali"]],["Smalltalk",["smalltalk","squeak"]],["Smarty",["smarty"]],["Snobol",["snobol"]],["SourcePawn",["sp"]],["Debian Sourcelist",["sourceslist","sources.list"]],["SQL",["sql"]],["sqlite3con",["sqlite3"]],["SquidConf",["squidconf","squid.conf","squid"]],["Scalate Server Page",
["ssp"]],["Stan",["stan"]],["systemverilog",["sv"]],["Tcl",["tcl"]],["Tcsh",["tcsh","csh"]],["Tea",["tea"]],["TeX",["tex","latex"]],["Text",["text"]],["Treetop",["treetop"]],["UrbiScript",["urbiscript"]],["VGL",["vgl"]],["Vala",["vala","vapi"]],["aspx-vb",["aspx-vb"]],["VB.net",["vb.net","vbnet"]],["Velocity",["velocity"]],["verilog",["v"]],["vhdl",["vhdl"]],["VimL",["vim"]],["XQuery",["xquery","xqy","xq","xql","xqm"]],["XML",["xml"]],["XSLT",["xslt"]],["Xtend",["xtend"]],["YAML",["yaml"]]];
function ME(a){return{label:a[0],value:a[1][0],toString:mf(a[0])}}var NE=y.map(LE,ME);r=KE.prototype;r.V={wS:"lang-select",$p:"collapsed",GO:"lang-list",bR:"lang-option",wk:"active",uB:"checked"};r.m=function(){KE.g.m.call(this);this.e().w();this.T.w();L(this.d);this.Lq=this.nt=this.d=j};r.j=function(){var a=this.s;this.d=K("div",{innerHTML:this.ce,className:[a.wS,a.$p].join(" ")})};r.ce='<div class="title-button">选择语言</div><i class="zg-icon zg-icon-double-arrow"></i><div class="input-wrapper"><input class="filter-input zg-form-text-input" placeholder="搜索语言"></div>';
r.p=function(){KE.g.p.call(this);this.nt=I("title-button",this.d);this.Lq=I("filter-input",this.d);vg(this.nt,i);var a=this.Lq,b=this.d,c=this.s,d=this.e(),f=this,g=f.s,k={},m=new JE(NE,l),b=new zp(b,k),q=new pp(j,j,l),s=m.ei;m.ei=function(a,b,c){Oa(a)?s.apply(this,arguments):c(a,NE)};k.Rj=function(a,b,c){a=a.data;a.value===f.rc&&(E.add(c,g.uB),c.appendChild(K("i","icon "+g.uB)));c.appendChild(document.createTextNode(a.toString()))};var x=new $o(m,b,q);q.T=x;q.Ek(a);x.Tf=20;d.c(x,"suggestionsupdate",
function(){x.xe(x.vc+0)}).c(x,"update",function(a){this.Wx(a.Fo)}).c(x,"dismiss",function(){this.Ug(i)});a=x.F;a.className=c.GO;a.Os=c.bR;a.au=c.wk;this.T=x;this.e().c(this.d,"click",this.Uq).c(this.nt,"click",this.mN)};r.O=n("rc");r.pa=function(a){var b=a&&y.find(NE,function(b){return b.value===a});b&&(this.ii(b.label),this.dispatchEvent({type:"change",aR:b}));this.rc=a};
r.Uq=function(a){var b=this.T,c=b.F.f();c&&(document.activeElement!==this.Lq&&!c.contains(a.target))&&(a.preventDefault(),a.stopPropagation(),fp(b))};r.mN=function(){this.isCollapsed()&&this.Ug(l)};r.isCollapsed=function(){return E.has(this.d,this.s.$p)};r.Ug=function(a){if(this.isCollapsed()!==a){var b=this.Lq,c=this.s;a?E.add(this.d,c.$p):(E.remove(this.d,c.$p),a=this.T,c=a.F,a.Pl(NE),c.f().scrollTop=0,c.show(),b.value="",b.focus())}};r.ii=function(a){var b=this.nt;b.title=a;zc(b,a)};
r.Wx=function(a){this.pa(a.value);this.T.uc()};function OE(a){Ds.call(this);F.extend(this.s={},this.V,a||{});this.Av=this.rb=j}w(OE,Ds);var PE=B||tb||A;function QE(a){return"P"===a.tagName}function RE(a){return 3===a.nodeType}function SE(a){return a&&"PRE"===a.tagName}
function TE(a){function b(a){return y.contains(f,a)}function c(){var a=document.createTextNode("\n");f.push(a);return a}var d=document.createElement("div");d.innerHTML=a;var f=[],g=rf(b),a=Ac(d,BC);(0,y.forEach)(a,function(a){a.lastChild&&"BR"===a.lastChild.tagName&&a.removeChild(a.lastChild);a.firstChild||a.appendChild(document.createTextNode(""));a.insertBefore(c(),a.firstChild);a.appendChild(c())});a=y.toArray(d.getElementsByTagName("br"));(0,y.forEach)(a,function(a){a!==a.parentNode.lastChild&&
oc(document.createTextNode("\n"),a)});d=Ac(d,RE);d=qf(function(a){return y.filter(a,function(c,d){var f=a[d-1];return!f||!(b(f)&&b(c))})},function(a){var b=y.Ev(a,g);return-1!==b?a.slice(0,b+1):a},function(a){var b=y.Mq(a,g);return-1!==b?a.slice(b):a})(d);return(0,y.map)(d,function(a){return a.nodeValue}).join("").replace(/\xa0/g," ")}r=OE.prototype;r.Wc=mf("CodePlugin");r.De=function(a){return"+code"===a};r.Ve=function(a){this.De(a)&&this.trigger()};
r.queryCommandValue=function(){var a="1"===UE(this).state,b=this.o.Hc.EnterHandler;b&&(a?b.disable(this.o):b.enable(this.o));this.rb&&this.Av&&Kg(this.rb,function(b){b instanceof Oh&&b.Pa(!a||y.contains(this.Av,b.Sd()))},this);return a};r.V={TK:""};r.JG=function(a){this.rb=a;this.Av=["toggleFullScreen"].concat("+code")};r.m=function(){OE.g.m.call(this);this.rb=j};function VE(a,b,c){for(a=a.o.field;b!==a;){if(c(b))return b;b=b.parentNode}}
function UE(a){var b,c=Ar();c&&a.o.field.contains(c.Db())?(b=c.M(),a=(b=VE(a,b,SE))?"1":"2"):a="0";return{state:a,zo:c,code:b}}
r.trigger=function(){var a=UE(this),b=a.zo,c=a.code;switch(a.state){case "1":var d=!Oa(Ic(c)),a=DC(c);d?(c.parentNode.removeChild(c),a&&ls(a,i)):(b=b.M()&&b.ba()?new lC(b):j,d=Qa(c.innerHTML),gs(O.filter(new bs(c,l,i),hs))&&(d="<br>"+d),a&&"BR"!==a.tagName&&(d+="<br>"),a=gc(d),c.parentNode.replaceChild(a,c),b.restore());break;case "2":this.vr(b,Oa(b.Ze())?TE(b.Ud()):PE?"\n":"")}};
r.$m=function(a,b){var c=document.createElement(a);c.id=Eg(Dg.v());return b(c,function(){c=H(c.id);c.removeAttribute("id");return c})};
r.vf=function(){var a=this.o,b=this.o.field,c,d=new Jo(SE,l,j,b),f=K("div",{style:"display:none"});to(d,new Nf(4,0,0,0));d.ql=new Nf(4,0,0,0)||j;d.at=150;d.gr=100;d.bg(f);d.className="hc-lang-select";N(d,"beforeshow",function(a){c=a.target.anchor;d.Kc(new Bi(c,1));if(c.lang){var a=g,b,f=c.lang;(b=(b=y.find(LE,function(a){return a[0]===f||y.contains(a[1],f)}))&&ME(b))&&a.pa(b.value);g.Ug(i)}else g.ii("选择语言")});N(d,"beforehide",function(a){c=j;g.pa(j);if((a=a.target)&&b.contains(a)&&SE(a))return l});
var g=new KE;g.N(f);N(g,"change",function(a){c&&(c.lang=a.aR.value,d.n(l))});this.Yt={Qv:mf(d),MX:mf(g)};N(a,"delayedchange",this.aS,l,this);N(a.field,"paste",this.rw,l,this)};r.aS=function(){var a=this.Yt&&this.Yt.Qv();a&&(a.H()&&a.anchor)&&a.xa()};
r.rw=function(a){var b=UE(this),c=b.zo,d=b.code;if("1"===b.state)if(b=a.Yb.clipboardData)b.types&&y.contains(b.types,"text/plain")&&(a.preventDefault(),b=b.getData("text/plain"),a=document.createTextNode(b),c.Zf(a),ls(a));else if(window.clipboardData){if(b=window.clipboardData.getData("Text")){a.preventDefault();var f=b;this.$m("i",function(a,b){c.Zf(a);a=b();f=Ma(f);oc(document.createTextNode(f),a)})}}else{var g=c.ma(),a=c.Ze().length,k=(d.firstChild?is(d.firstChild):0)-g-a;setTimeout(function(){var a=
TE(d.innerHTML);zc(d,a);a=(d.firstChild?is(d.firstChild):0)-k;d.firstChild&&Dr(d.firstChild,Math.max(g,a)).select()})}};
r.ow=function(a){if(13===a.keyCode)return this.iw(a);if(40===a.keyCode){var b=UE(this),c=b.zo,a=b.code;if("1"===b.state){for(var d=b=c.ba(),f=[];d&&d!==a;)f.push([d.parentNode.childNodes.length,y.indexOf(d.parentNode.childNodes,d)]),d=d.parentNode;f=!f.length||y.every(f,function(a){return a[0]===a[1]+1});d=RE(b);if(f&&!(f=!d))d&&(b=b.nodeValue,c=c.Ba(),d=c===b.length||PE&&c===b.length-1&&"\n"===b.slice(-1)),f=d;f&&(DC(a)||mc(document.createElement("br"),a))}}};
r.iw=function(a){var b=UE(this),c=b.zo;if("1"===b.state)return a.preventDefault(),z?this.$m("i",function(a,b){c.Zf(a);setTimeout(function(){var c=document.createTextNode("\r");a=b();oc(c,a);ls(c)})}):document.queryCommandSupported("insertLineBreak")?document.execCommand("insertLineBreak"):(a=document.createTextNode("\n"),c.insertNode(a),ls(a)),this.o.Se(),i};
r.vr=function(a,b){var c=this.s,d;a.Ic();var f;var g=nC(a,i),k=g.X,m,q=this.o.field;f=VE(this,k,FC(BC,rf(QE)))||q;var s=function(a){return a.parentNode.insertBefore(document.createTextNode(""),a)};if(RE(k)){var x=k.parentNode;!k.nodeValue&&x!==q&&CC(x)?(m=s(x),k=s(m),x.parentNode.removeChild(x)):m=z&&g.offset===k.length?mc(document.createTextNode(""),k):k.splitText(g.offset)}else"BR"===k.tagName&&(m=k,k=s(k));if(m){for(var C,g=k,k=m;g!=f&&(C=g.parentNode);){m=g;g=k;for(k=C.cloneNode(l);m.nextSibling;)k.appendChild(m.nextSibling);
g&&k.insertBefore(g,k.firstChild);g=C}C=k;m=C.firstChild;jc(f,C.childNodes);f=m}else f=j;f?(d=document.createElement("PRE"),f.parentNode.insertBefore(d,f)):this.$m("PRE",function(b,c){a.insertNode(b);d=c()});!b&&z&&(b=" ");d.lang=c.TK;zc(d,b);CC(d)?ks(d.firstChild):ls(d.lastChild);c=d;DC(c)||mc(document.createElement("br"),c)};rk["+code"]={Va:i,K:"插入代码",qa:"+code",Da:"tr-icon tr-code",factory:sj};function WE(a){wD.call(this,a);this.G=new me(this);this.Vz="http://upload."+Ak.Sl+":"+location.port+"/upload";this.YJ=!z}w(WE,wD);function XE(a){ad.call(this,"ok");var b=a[0];this.rl=b;this.LF=b.replace("_m.jpg","_r.jpg");this.cG=a[1];this.bG=a[2]}w(XE,ad);r=WE.prototype;r.ce=Mn('<div class="zm-img-uploader"><iframe src="about:blank" name="av_up_frame" style="position: absolute; height: 0; width: 0; left: -9000px; "></iframe><div class="zg-section zm-img-uploader-tab"><a href="javascript:;" class="tab-nav selected">上传图片</a> 或 <a href="javascript:;" class="tab-nav">引用站外图片</a></div><form class="zg-clear" target="av_up_frame" method="POST" enctype="multipart/form-data" action="<%= uploadURL %>"><div class="tab-content selected <% if (canStylize) { %>inline<% } %>"><% if (canStylize) { %><input type="file" name="upload_file" style="opacity:0;height:0;width:0;font-size:0;position:absolute;"><a href="javascript:;" class="browser zg-btn-blue">选择图片</a><% } else { %><input type="file" name="upload_file"><% } %></div><div class="tab-content"><input type="text" autocomplete="off" name="upload_file_url" class="zm-editable-editor-input zg-form-text-input"><a href="javascript:;" class="insert zg-btn-blue zm-uploader-button-fix">确认</a></div><span style="display: none; " class="zm-img-uploader-loading">正在上传</span><span style="display: none; " class="zm-img-uploader-error">上传图片失败，请稍后重试</span></form><div class="zg-gray">请不要上传与回答问题无关的图片，详细请看 <a href="http://www.zhihu.com/question/20064580" target="_blank">知乎图片使用规范</a></div><div class="zm-command"><a class="cancel" href="javascript:;">取消</a></div></div>');
r.Vu=function(){var a=gc(this.ce({uploadURL:this.Vz,canStylize:this.YJ}));F.forEach({form:"form",Dz:".zm-img-uploader-tab",Ng:".zm-img-uploader-loading",Ue:".zm-img-uploader-error",jH:"input[type=text]",rn:"input[type=file]",lB:".browser",Hk:".cancel",eO:".insert"},function(b,d){this[d]=$(b,a).get(0)},this);this.G.c(U,"iframe_data",this.iu).c(this.rn,"change",this.wR).c(this.eO,"click",this.fO).c(this.Hk,"click",function(){this.dw();this.hide()}).c(this.Dz,"click",function(a){a=$(a.target);a.is("a")&&
!a.is(".selected")&&YE(this,a.index())});this.DB=a;Gl||(YE(this,1),$(this.Dz).replaceWith("<strong>输入站外图片地址：</strong>"));this.lB&&this.G.c(this.lB,"click",function(){this.rn.click()});var b=new xD(this);b.Ma("插入图片").Fa(this.DB);b=AD(b);nl(b,j);return b};r.wR=function(){if(this.rn.value){var a=this.rn.value,a=String(a).toLowerCase();(!a?0:y.some([".jpg",".jpeg",".gif",".png"],function(b){return Ga(a,b)}))?(this.jH.value="",S(this.Ng,i),S(this.Ue,l),this.form.submit()):ZE(this,"图片不是 .jpg、.png 或 .gif 格式，无法上传。")}};
r.fO=function(){var a=pn(this.jH.value);a?Fa(a,"http://")?(this.rn.value="",S(this.Ng,i),S(this.Ue,l),this.form.submit()):ZE(this,"我们目前不支持该协议。"):ZE(this,"请填写图片地址。")};function YE(a,b){function c(a){a.eq(b).addClass("selected").siblings().removeClass("selected")}var d=$(".tab-nav",a.Dz),f=$(".tab-content",a.form);S(a.Ue,l);var g=f.eq(b);g.find("input").val("");c(d);c(f);g.find(":text").focus()}function ZE(a,b){S(a.Ng,l);a.Ue.innerHTML=b;S(a.Ue,i)}r.iu=function(a){S(this.Ng,l);this.Zj(a.lb)};
r.Zj=function(a){a&&!a.r?(this.dispatchEvent(this.an(a.msg)),this.hide()):ZE(this,a.msg)};r.an=function(a){return new XE(a)};r.m=function(){this.G.w();this.G=j;WE.g.m.call(this)};function $E(){BD.call(this,"image");this.G=new me(this)}w($E,BD);r=$E.prototype;r.Wc=mf("ImageDialogPlugin");r.Ve=function(a,b){var c=this.o;return!c.Ce&&(c.Jf(),!c.Ce)?l:$E.g.Ve.call(this,a,b)};
r.gj=function(a){if(a&&"mouseup"===a.type){var b=a.target;b&&"IMG"===b.nodeName&&(a=DC(b),a||(a=document.createElement("br"),mc(a,b)),ks(a))}};r.zn=function(a){$E.g.zn.call(this,a)};r.Uu=function(a){a=new WE(a);this.G.c(a,"ok",this.ej).c(a,"cancel",this.An);return a};r.m=function(){$E.g.m.call(this);this.G.w()};
r.ej=function(a){DD(this);var b=iC(this),c;c=a.LF?b.j("IMG",{"class":"origin_image zh-lightbox-thumb","data-original":a.LF,title:"点击查看原图",src:a.rl}):b.j("IMG",{"class":"content_image",src:a.rl});a.cG&&c.setAttribute("data-rawwidth",a.cG);a.bG&&c.setAttribute("data-rawheight",a.bG);a=ft(this.o);if(yC(a))a.Zf(c),z||(ls(c,l),b.Ja().focus()),Hs(this.o),this.o.Se();else return j;this.G.Ac()};r.An=function(){this.G.Ac()};function aF(a){wD.call(this,a);this.G=new me(this)}w(aF,wD);function bF(a,b,c,d,f){ad.call(this,"ok");this.iU=a;this.gU=b;this.hU=f;this.XS=c;this.poster=d}w(bF,ad);r=aF.prototype;r.show=function(){aF.g.show.call(this);this.Ct.focus()};r.hide=function(){aF.g.hide.call(this)};
r.Vu=function(){var a="http://upload."+Ak.Sl+":"+location.port+"/upload_video",a=this.Uc.j("div","zm-img-uploader zm-img-uploader-upload-tab-selected",[this.Uc.j("div","zg-section",this.Uc.j("strong",j,"输入视频页地址：")),this.vR=this.Uc.j("iframe",{id:"video_up_frame",src:"about:_blank",name:"video_up_frame",style:"visible:hidden;position:absolute;height:0;width:0;left:-9000px"}),this.Hh=this.Uc.j("form",{"class":"zg-section-title",target:"video_up_frame",method:"post",enctype:"multipart/form-data",action:a},
[this.Ct=this.Uc.j("input",{type:"text","class":"zg-form-text-input",name:"upload_file_url",autocomplete:"off"}),this.Ym=this.Uc.j("a",{"class":"zg-btn-blue zm-uploader-button-fix",name:"save",href:"javascript:;"},"确定"),this.Uc.j("div","zm-video-uploader-info",[this.Ng=this.Uc.j("span",{style:"display:none","class":"zm-img-uploader-loading"},"正在上传"),this.Ue=this.Uc.j("span",{style:"display:none","class":"zm-img-uploader-error"},"插入视频失败，请稍后重试")])]),this.QN=this.Uc.j("div","zg-gray"),this.qg=this.Uc.j("div",
"zm-command",[this.Hk=this.Uc.j("a",{href:"javascript:;"},"取消")])]);this.QN.innerHTML='我们目前支持<a class="zg-link-gray" target="_blank" href="http://youku.com">优酷</a>、<a class="zg-link-gray" target="_blank" href="http://tudou.com">土豆</a>、<a href="http://video.sina.com.cn/" class="zg-link-gray" target="_blank">新浪</a>视频服务。<br />请不要上传与回答问题无关的视频，详细请看 <a href="http://www.zhihu.com/question/20118966" target="_blank">知乎视频使用规范</a>';this.G.c(this.Hk,"click",function(){this.dw();this.hide()}).c(this.Ym,"click",
this.WF).c(this.qg,"click",this.S).c(this.Hh,"submit",function(){return cF(this,this.Ct.value)}).c(U,"iframe_data",this.iu);this.DB=a;var b=new xD(this);b.Ma("插入视频").Fa(a);a=AD(b);nl(a,j);return a};function cF(a,b){b=pn(b);if(!b)return l;var c=b.match(/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]{2,256}\.[a-z]{2,4}\b(\/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)?/gi);c||(S(a.Ng,l),a.Ue.innerHTML="我们无法识别你输入的视频页地址",S(a.Ue,i));return c}
r.WF=function(){if(this.Ct.value){var a=pn(this.Ct.value);a&&cF(this,a)&&(S(this.Ng,i),S(this.Ue,l),this.Hh.submit())}};r.S=function(a){"save"===(a.target&&a.target.name)&&this.WF()};r.iu=function(a){S(this.Ng,l);this.Zj(a.lb)};r.Zj=function(a){a&&!a.r?(this.dispatchEvent(this.an(a.msg[0],a.msg[1],a.msg[2],a.msg[3],a.msg[4])),this.hide()):(a=a.msg,S(this.Ng,l),this.Ue.innerHTML=a,S(this.Ue,i))};r.an=function(a,b,c,d,f){return new bF(a,b,c,d,f)};r.m=function(){this.G.w();this.G=j;aF.g.m.call(this)};
function dF(){BD.call(this,GC);this.G=new me(this)}w(dF,BD);r=dF.prototype;r.Wc=mf("VideoDialogPlugin");r.Ve=function(a,b){var c=this.o;return!c.Ce&&(c.Jf(),!c.Ce)?l:dF.g.Ve.call(this,a,b)};r.zn=function(a){dF.g.zn.call(this,a)};r.Uu=function(a){a=new aF(a);this.G.c(a,"ok",this.ej).c(a,"cancel",this.An);return a};r.m=function(){dF.g.m.call(this);this.G.w()};
r.ej=function(a){DD(this);var b=iC(this),c=b.j("embed");F.forEach({type:"application/x-shockwave-flash",allowscriptaccess:"always",allowfullscreen:"true",wmode:"opaque","class":"video",width:"420",height:"350",src:a.iU,"data-poster":a.poster,"data-name":a.hU,"data-videoid":a.gU,"data-sourceurl":a.XS},function(a,b){c.setAttribute(b,a)});a=fC(c);Ga(a,'">')&&(a+="</embed>");var a=gc(a+" "),d=a.firstChild,f=ft(this.o);if(yC(f))f.Zf(a),z?document.selection&&(b=document.selection.createRange(),b.move("character",
-1),b.select()):(ls(d),b.Ja().focus()),Hs(this.o),this.o.Se();else return j;this.G.Ac()};r.An=function(){this.G.Ac()};var Ir=i,eF=Ds.prototype.execCommand,fF=["+insertOrderedList","+insertUnorderedList","+link"];Ds.prototype.execCommand=function(a){var b=this.o;return y.contains(fF,a)&&!b.Ce&&(b.Jf(),!b.Ce)?l:eF.apply(this,arguments)};var gF=BD.prototype.execCommand,hF=["+equation"];BD.prototype.execCommand=function(a){var b=this.o;return y.contains(hF,a)&&!b.Ce&&(b.Jf(),!b.Ce)?l:gF.apply(this,arguments)};GC="video";EC=mb?"⌘":"ctrl";rk[GC]={qa:GC,K:"插入视频",Da:"tr-icon tr-video",factory:qj};
rk["+equation"]={qa:"+equation",K:xj.HV,Da:"tr-icon tr-equation",factory:qj};rk["+bold"].K="粗体 ("+EC+"+b)";rk["+italic"].K="斜体 ("+EC+"+i)";rk["+underline"].K="下划线 ("+EC+"+u)";rk["+superscript"].K="引用内容";rk["+insertOrderedList"].K="有序列表";rk["+insertUnorderedList"].K="无序列表";rk["+removeFormat"].K="清除格式";rk.image.K="插入图片";rk[GC].K="插入视频";rk["+equation"].K="插入公式";function iF(){}
iF.prototype.wg=function(a,b){this.zB=b;var c,d,f;d=I("zm-editable-toolbar-container",a);c=I("zm-editable-editor-outer",a);f=I("zm-editable-editor-field-element",a);var g=new lt(f.id);g.PJ=89;var k=[];b.enableFullScreen&&k.push("toggleFullScreen");k.push("+bold","+italic","+underline",new XD,"+blockquote","+code","+insertOrderedList","+insertUnorderedList","+equation");b.canUploadMedia_&&k.push(new XD,"image",GC);b.useRemoveFormat_&&k.push(new XD,"+removeFormat");var m=Sb(d);f=[];for(var q=0,s;s=
k[q];q++){if(t(s)){var x=h;if(s=rk[s]){var x=s.factory||sj,C=s.qa,J=s.K,G=s.caption,P=s.Da,W=m||Sb(),x=x(C,J,G,P,j,W);s.Va&&(x.Va=i)}s=x}s&&f.push(s)}var k=Sb(d),ma=new tC(Hh.v(),ph,k),k=gg(d);ma.ji(k);ma.Ie(l);for(m=0;q=f[m];m++)ih(q,32,l),q.ji(k),ma.aa(q,i);ma.N(d);new YD(g,ma);hC(g,new JC);hC(g,new GD);if(b.loremIpsum_&&(hC(g,new HD(b.loremIpsum_)),A))g.on("load",function(){pd(g.f(),"focus",function(){g.execCommand("clearlorem",i)})});hC(g,new bD);hC(g,new ID);hC(g,new RD);var Ha=new OE;hC(g,Ha);
hC(g,new $E);hC(g,new dF);hC(g,new xE);hC(g,new tE);hC(g,new uE);hC(g,new HE);b.enableFullScreen&&(c=new fB({title:"写作模式",kk:c}),hC(g,c));g.on("load",function(){b.useScraper_&&this.ur(g,ma);Ha&&(Ha.JG(ma),Ha.vf())},l,this);return[g,ma]};iF.prototype.ur=function(a,b){var c=a.f(),d=new Ut;d.h(c);var f=K("div",{style:"display:none",className:"tr-spinner"});b.f().appendChild(f);d.on("willScrape",function(){S(f,i)}).on("didScrape",function(){S(f,l)})};
Da("ZH.createRichTextEditor",function(a,b){var c=j,c=new iF;return c.wg(a,b)});Ef("rich_text_editor");
//@ sourceURL=/static/js/c/1303291140368123/rich_text_editor.js